import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.57.0";

const U=Deno.env.get("SUPABASE_URL")??"",K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??"",T=Deno.env.get("TELEGRAM_BOT_TOKEN")??"",G=Deno.env.get("GEMINI_API_KEY")??"";
const HEAVY=Deno.env.get("GEMINI_MODEL")??"gemini-3.6-flash",FAST=Deno.env.get("GEMINI_FAST_MODEL")??"gemini-3.5-flash-lite";
const db=createClient(U,K,{auth:{persistSession:false,autoRefreshToken:false}}),CORE=`${U}/functions/v1/telegram-webhook`;
const ADMIN=new Set(["admin","owner"]),VISIT_WRITE=new Set(["admin","owner","editor","supervisor"]);
const c=(v:any,n=5000)=>String(v??"").replace(/[\u0000-\u001f\u007f]/g," ").trim().slice(0,n);
const nm=(v:any)=>String(v??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9ñ]+/g," ").replace(/\s+/g," ").trim();
const j=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{"content-type":"application/json","cache-control":"no-store"}});
const day=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"America/Tegucigalpa",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
const money=(v:any)=>`L. ${Number(v||0).toLocaleString("es-HN",{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const dateHN=(v:any)=>{const s=String(v??"");const m=s.match(/^(\d{4})-(\d{2})-(\d{2})/);return m?`${m[3]}/${m[2]}/${m[1]}`:(s||"No registrada")};
async function h(v:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return[...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function tg(m:string,b:any){const r=await fetch(`https://api.telegram.org/bot${T}/${m}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(b)}),d=await r.json();if(!r.ok||d?.ok===false)throw new Error(d?.description||`Telegram ${r.status}`);return d}
const send=(chat:any,text:string,k?:any)=>tg("sendMessage",{chat_id:chat,text:c(text,3900),disable_web_page_preview:true,...(k?{reply_markup:k}:{})});
const typing=(chat:any)=>tg("sendChatAction",{chat_id:chat,action:"typing"}).catch(()=>null);
async function core(u:any){return fetch(CORE,{method:"POST",headers:{"content-type":"application/json","x-telegram-bot-api-secret-token":await h(T)},body:JSON.stringify(u)})}
function type(m:any){if(m?.voice)return"voice";if(m?.audio)return"audio";if(m?.photo)return"photo";if(m?.document)return"document";if(m?.location)return"location";if(m?.text?.startsWith("/"))return"command";return m?.text||m?.caption?"text":"other"}
function fi(m:any){if(m?.voice)return{id:m.voice.file_id,u:m.voice.file_unique_id,m:m.voice.mime_type||"audio/ogg",n:`voice_${m.message_id}.ogg`};if(m?.audio)return{id:m.audio.file_id,u:m.audio.file_unique_id,m:m.audio.mime_type||"audio/mpeg",n:m.audio.file_name||`audio_${m.message_id}.mp3`};if(m?.document)return{id:m.document.file_id,u:m.document.file_unique_id,m:m.document.mime_type||"application/octet-stream",n:m.document.file_name||`document_${m.message_id}`};if(m?.photo?.length){const p=m.photo[m.photo.length-1];return{id:p.file_id,u:p.file_unique_id,m:"image/jpeg",n:`photo_${m.message_id}.jpg`}}return{id:null,u:null,m:null,n:null}}
async function dl(id:string){const x=await tg("getFile",{file_id:id}),p=x?.result?.file_path;if(!p)throw new Error("Telegram no devolvió la ruta del archivo");const r=await fetch(`https://api.telegram.org/file/bot${T}/${p}`);if(!r.ok)throw new Error("No se pudo descargar el archivo");const b=new Uint8Array(await r.arrayBuffer());if(b.byteLength>18*1024*1024)throw new Error("El archivo supera 18 MB");return b}
function b64(b:Uint8Array){let s="";for(let i=0;i<b.length;i+=32768)s+=String.fromCharCode(...b.subarray(i,Math.min(i+32768,b.length)));return btoa(s)}
async function gem(input:any,model=FAST){if(!G)throw new Error("Gemini no está configurado");const r=await fetch("https://generativelanguage.googleapis.com/v1beta/interactions",{method:"POST",headers:{"content-type":"application/json","x-goog-api-key":G,"Api-Revision":"2026-05-20"},body:JSON.stringify({model,input})}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(c(d?.error?.message||`Gemini ${r.status}`,500));return d}
function out(d:any){const z:string[]=[];const a=(x:any)=>{if(typeof x==="string"&&x.trim())z.push(x.trim())};a(d?.output_text);for(const x of d?.output||[]){a(x?.text);for(const y of x?.content||[])a(y?.text)}for(const s of d?.steps||[])for(const q of[s?.model_output,s?.output,s]){a(q?.text);a(q?.output_text);for(const x of q?.content||[]){a(x?.text);for(const y of x?.parts||[])a(y?.text)}}return[...new Set(z)].join("\n")}
function pj(t:any){try{let s=String(t||"").replace(/^```(?:json)?\s*/i,"").replace(/\s*```$/i,"");const a=s.indexOf("{"),b=s.lastIndexOf("}");if(a>=0&&b>a)s=s.slice(a,b+1);return JSON.parse(s)}catch{return null}}
function evidenceReply(a:any,kind:string){const lines:string[]=["🧠 ANÁLISIS DE EVIDENCIA"];const label=kind==="photo"?"Fotografía":/voice|audio/.test(kind)?"Audio":"Documento";lines.push(`Tipo: ${label}`);if(a?.summary)lines.push(`\nResumen: ${c(a.summary,900)}`);const add=(title:string,items:any)=>{if(!Array.isArray(items)||!items.length)return;lines.push(`\n${title}:`);for(const item of items.slice(0,5))lines.push(`• ${c(item,450)}`)};add("Observaciones",a?.observations);add("Riesgos",a?.risks);add("Recomendaciones",a?.recommendations);add("Datos que requieren verificación",a?.needs_verification);lines.push("\n✅ Evidencia guardada en el proyecto activo.");return lines.join("\n")}

const linkCache=new Map<string,{at:number,v:any}>(),roleCache=new Map<string,{at:number,v:any}>();
async function link(tid:any){const k=String(tid),x=linkCache.get(k);if(x&&Date.now()-x.at<60000)return x.v;const {data}=await db.from("telegram_links").select("id,workspace_id,user_id,current_project_id,status").eq("telegram_user_id",tid).eq("status","active").limit(1).maybeSingle();if(data)linkCache.set(k,{at:Date.now(),v:data});return data}
async function role(l:any){const k=l.id,x=roleCache.get(k);if(x&&Date.now()-x.at<60000)return x.v;const {data}=await db.from("workspace_members").select("role,active").eq("workspace_id",l.workspace_id).eq("user_id",l.user_id).maybeSingle();const v=data?.active?data:null;if(v)roleCache.set(k,{at:Date.now(),v});return v}
async function session(id:string){const {data}=await db.from("assistant_visit_sessions").select("*").eq("telegram_link_id",id).in("status",["active","review"]).order("created_at",{ascending:false}).limit(1).maybeSingle();return data}
async function search(ws:string,q:string,n=5){const {data,error}=await db.rpc("telegram_project_search",{p_workspace_id:ws,p_query:q,p_limit:n});if(error)throw error;return data||[]}
function pick(rows:any[]){if(!rows.length)return null;const a=rows[0],b=rows[1],s=Number(a.match_score||0),s2=Number(b?.match_score||0);return s>=100||(s>=65&&(!b||s-s2>=22))?a:null}
async function resolveProject(l:any,text:string,allowCurrent=true){const rows=await search(l.workspace_id,text,5),p=pick(rows);if(p)return p;if(allowCurrent&&l.current_project_id){const {data}=await db.from("projects").select("id: id,code,name,location,status,budget_estimate").eq("id",l.current_project_id).is("archived_at",null).maybeSingle();return data?{project_id:data.id,...data}:null}return null}
function reEsc(v:string){return String(v||"").replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}
function cleanProjectName(p:any){let name=c(p?.name||"Proyecto",260),code=c(p?.code||"",80);if(code){const e=reEsc(code);name=name.replace(new RegExp(`(?:[\\s,·—–-]+)?${e}\\s*$`,"i"),"").replace(new RegExp(`^${e}(?:\\s*[·,:—–-]\\s*|\\s+)`,"i"),"").trim()}name=name.replace(/^CONSTRUCCI[ÓO]N DE\s+/i,"").replace(/\s+SANTA\s+MAR[IÍ]A\s*$/i,"").replace(/\s+HACIA\s+/ig," → ").toLowerCase().replace(/\bbo\.\s*/ig,"Bo. ").replace(/\s+/g," ").trim();return name?name.charAt(0).toUpperCase()+name.slice(1):"Proyecto"}
function roleLabel(v:any){const x=String(v||"").toLowerCase();if(x==="admin")return"Admin";if(x==="owner")return"Propietario";if(x==="supervisor")return"Supervisor";if(x==="editor")return"Editor";if(x==="viewer")return"Consulta";return x?x.charAt(0).toUpperCase()+x.slice(1):"Usuario"}
const line=(p:any)=>`${p.code?`${p.code} · `:""}${cleanProjectName(p)}`;
function statusKB(active:boolean){const rows:any[]=[[{text:"📋 Ver proyecto",callback_data:"st:project"},{text:"📸 Visita actual",callback_data:"st:visit"}],[{text:"📄 Generar informe",callback_data:"st:report"}]];if(active)rows.push([{text:"❌ Finalizar visita",callback_data:"st:close"}]);return{inline_keyboard:rows}}
async function snap(l:any,pid:string){const {data,error}=await db.rpc("telegram_project_snapshot",{p_workspace_id:l.workspace_id,p_project_id:pid});if(error)throw error;if(data?.contract){const {data:detail}=await db.from("contracts").select("signature_date,advance_payment_date").eq("workspace_id",l.workspace_id).eq("project_id",pid).is("voided_at",null).order("created_at",{ascending:false}).limit(1).maybeSingle();if(detail)data.contract={...data.contract,...detail}}return data}

function isFact(t:string){const n=nm(t);return /\b(estado|estatus|monto|presupuesto|contratado|contratista|contrato|firma|plazo|vence|vencimiento|finalizacion|dias|visitas|ultima visita|pagado|pagos|pago|estimacion|estimaciones|garantia|garantias|anticipo)\b/.test(n)}
function factReply(s:any,t:string){const n=nm(t),p=s?.project||{},co=s?.contract||{},r:string[]=[];r.push(`📌 ${p.code||""} · ${cleanProjectName(p)}`);if(/estado|estatus|situacion/.test(n))r.push(`Estado: ${p.status||"No registrado"}.`);if(/monto|presupuesto|contratado/.test(n)){const amount=co.original_amount??p.budget_estimate;r.push(`Monto contratado: ${amount!=null?money(amount):"No registrado"}.`)}if(/contratista/.test(n))r.push(`Contratista: ${co.contractor||"No registrado"}.`);if(/firma/.test(n))r.push(`Fecha de firma: ${dateHN(co.signature_date)}.`);if(/contrato/.test(n)&&!/contratista|monto contratado/.test(n))r.push(`Contrato: ${co.number||"No registrado"}${co.status?` · ${co.status}`:""}.`);const asksTerm=/plazo|vence|vencimiento|dias/.test(n);const asksEnd=/finalizacion|fecha final/.test(n);if(asksTerm)r.push(`Plazo de ejecución: ${co.execution_days??p.execution_days??"No registrado"} días${co.end_date||p.end_date?` · finalización ${dateHN(co.end_date||p.end_date)}`:""}.`);else if(asksEnd)r.push(`Fecha de finalización: ${dateHN(co.end_date||p.end_date)}.`);if(/visita/.test(n))r.push(`Visitas registradas: ${s.visit_count||0}${s.latest_visit?` · última N.º ${s.latest_visit.visit_number} del ${dateHN(s.latest_visit.visit_date)}`:""}.`);const asksGeneralPayments=/\b(pagos|total pagado)\b/.test(n)&&!/anticipo/.test(n);if(asksGeneralPayments)r.push(`Pagos registrados: ${money(s.payments_total)} (${s.payments_count||0}).`);if(/estimacion/.test(n))r.push(`Estimaciones: ${s.estimate_count||0} · bruto ${money(s.estimates_gross)} · neto ${money(s.estimates_net)}.`);if(/garantia/.test(n))r.push(`Garantías registradas: ${s.guarantee_count||0}.`);if(/anticipo/.test(n))r.push(`Anticipo pagado: ${co.advance_paid!=null?money(co.advance_paid):"No registrado"}${co.advance_status?` · ${co.advance_status}`:""}${co.advance_payment_date?` · ${dateHN(co.advance_payment_date)}`:""}.`);return r.join("\n")}

function reportType(text:string){const n=nm(text);if(/visita|supervision|campo/.test(n))return"visitas";if(/financier/.test(n))return"financiero";if(/contractual|contrato/.test(n))return"contractual";if(/estimacion|pago/.test(n))return"estimaciones";if(/garantia/.test(n))return"garantias";if(/adjudic|oferta|cierre/.test(n))return"adjudicacion";if(/recepcion/.test(n))return"recepcion";if(/liquidacion/.test(n))return"liquidacion";if(/integral|completo/.test(n))return"integral";return"general"}
function isReport(text:string){const n=nm(text);return /(genera|generar|crea|crear|prepara|preparar|haz|hacer|necesito|quiero)/.test(n)&&/(informe|reporte|documento|acta|liquidacion|estimacion)/.test(n)}
function formatKB(id:string){return{inline_keyboard:[[{text:"📄 PDF",callback_data:`rf:${id}:pdf`},{text:"📝 Word",callback_data:`rf:${id}:docx`}],[{text:"📄📝 PDF + Word",callback_data:`rf:${id}:both`}],[{text:"❌ Cancelar",callback_data:`cancel:${id}`}]]}}
async function reportStart(l:any,chat:any,text:string){const p=await resolveProject(l,text,true);if(!p){const opts=await search(l.workspace_id,text,4);await send(chat,`No pude identificar el proyecto con seguridad.${opts.length?`\n\nPosibles:\n${opts.map(line).join("\n")}`:""}`);return}const rt=reportType(text),since=new Date(Date.now()-2*3600000).toISOString();const {data:e}=await db.from("project_evidence").select("id").eq("project_id",p.project_id).gte("created_at",since).order("created_at",{ascending:false}).limit(20);const ids=(e||[]).map((x:any)=>x.id);const {data:d,error}=await db.from("assistant_drafts").insert({workspace_id:l.workspace_id,project_id:p.project_id,draft_type:"generate_report",title:`Informe · ${p.code||"Proyecto"}`,source_text:text,summary:"Solicitud de informe desde Telegram",parsed_data:{report_type:rt,evidence_ids:ids,request_text:text,context_text:"",visit_selection:null},status:"draft",created_by:l.user_id}).select("id").single();if(error)throw error;if(rt==="visitas"){const {data:v}=await db.from("visits").select("visit_number,visit_date,summary").eq("project_id",p.project_id).is("voided_at",null).order("visit_date",{ascending:false}).order("visit_number",{ascending:false}).limit(20);if(!v?.length){await send(chat,"Este proyecto todavía no tiene visitas registradas.");return}const rows=v.map((x:any)=>[{text:`📍 N.º ${x.visit_number} · ${x.visit_date}`,callback_data:`rv:${d.id}:${x.visit_number}`}]);rows.push([{text:"📚 Todas las visitas",callback_data:`rv:${d.id}:all`}]);rows.push([{text:"❌ Cancelar",callback_data:`cancel:${d.id}`}]);await send(chat,`📍 ¿Qué visita deseas incluir?\n\n📌 ${line(p)}\n📎 Evidencia reciente disponible: ${ids.length}.`,{inline_keyboard:rows})}else await send(chat,`📄 Informe preparado para generar\n\n📌 ${line(p)}\n📎 Evidencia reciente disponible: ${ids.length}.\n\n¿En qué formato?`,formatKB(d.id))}

async function inbox(l:any,u:any,m:any){const f=fi(m);const {data,error}=await db.from("assistant_inbox").upsert({workspace_id:l.workspace_id,telegram_link_id:l.id,user_id:l.user_id,project_id:null,telegram_update_id:u.update_id,telegram_message_id:m.message_id,telegram_chat_id:m.chat.id,message_type:type(m),text_content:c(m.text??m.caption??"",3000)||null,telegram_file_id:f.id,telegram_file_unique_id:f.u,mime_type:f.m,status:"processing",processing_started_at:new Date().toISOString(),payload:{}},{onConflict:"workspace_id,telegram_update_id"}).select("id").single();if(error)throw error;return data.id}
async function analyzeEvidence(e:any,pid:string){let inboxRow:any=null;try{const {data:i}=await db.from("assistant_inbox").select("telegram_file_id,telegram_chat_id").eq("id",e.inbox_id).single();inboxRow=i;if(!i?.telegram_file_id)throw new Error("Archivo de Telegram no disponible");const bytes=await dl(i.telegram_file_id);const ext=String(e.file_name||"archivo").replace(/[^a-zA-Z0-9._-]+/g,"_");const path=`${e.workspace_id}/${pid||"unassigned"}/${day()}/${Date.now()}_${ext}`;const up=await db.storage.from("telegram-evidence").upload(path,bytes,{contentType:e.mime_type||"application/octet-stream"});if(up.error)throw up.error;const media=e.evidence_type==="photo"?"image":/voice|audio/.test(e.evidence_type)?"audio":"document";const prompt='Analiza esta evidencia para supervisión de proyectos. Devuelve SOLO JSON {"transcript":"","summary":"","observations":[],"recommendations":[],"risks":[],"facts":[],"needs_verification":[]}. No inventes; en fotos describe solo lo visible.';const a=pj(out(await gem([{type:"text",text:prompt},{type:media,data:b64(bytes),mime_type:e.mime_type||"application/octet-stream"}],HEAVY)))||{summary:"Evidencia procesada",needs_verification:["El resultado no llegó en formato estructurado."]};await db.from("project_evidence").update({storage_path:path,size_bytes:bytes.byteLength,analysis:a,extracted_text:a.transcript||a.summary||null,verification_status:e.evidence_type==="photo"?"observed":"needs_verification"}).eq("id",e.id);await db.from("assistant_inbox").update({project_id:pid||null,status:"processed",processed_at:new Date().toISOString(),processing_started_at:null,error_message:null}).eq("id",e.inbox_id);if(i.telegram_chat_id)await send(i.telegram_chat_id,evidenceReply(a,e.evidence_type))}catch(err){const safeError=c(err instanceof Error?err.message:err,400);await db.from("project_evidence").update({analysis:{pending_analysis:true,error:safeError,summary:"Evidencia guardada; análisis pendiente"}}).eq("id",e.id);await db.from("assistant_inbox").update({status:"error",error_message:c(err instanceof Error?err.message:err,500),processed_at:new Date().toISOString(),processing_started_at:null}).eq("id",e.inbox_id);if(inboxRow?.telegram_chat_id)await send(inboxRow.telegram_chat_id,"⚠️ La evidencia quedó guardada, pero el análisis no pudo completarse en este momento. Puedes intentarlo nuevamente.")}}
async function queueMedia(l:any,u:any,m:any,pid:string|null,sid:string|null){const iid=await inbox(l,u,m),f=fi(m),t=type(m);const {data:e,error}=await db.from("project_evidence").insert({workspace_id:l.workspace_id,project_id:pid,inbox_id:iid,visit_session_id:sid,evidence_type:t,storage_path:null,mime_type:f.m,file_name:f.n,size_bytes:null,telegram_file_unique_id:f.u,analysis:{pending_analysis:true,summary:"Evidencia recibida; análisis en curso"},created_by:l.user_id,verification_status:"unreviewed",source_kind:t==="document"?"document":"telegram"}).select("*").single();if(error)throw error;await db.from("assistant_inbox").update({project_id:pid,status:"processed",processed_at:new Date().toISOString(),processing_started_at:null,payload:{evidence_id:e.id,pending_analysis:true}}).eq("id",iid);EdgeRuntime.waitUntil(analyzeEvidence(e,pid||""));return e}
async function addQuickEvidence(l:any,u:any,m:any,pid:string,sid:string|null){const iid=await inbox(l,u,m),t=type(m);let ext="",a:any={};if(t==="location"){ext=`${m.location.latitude}, ${m.location.longitude}`;a={summary:"Ubicación GPS registrada",latitude:m.location.latitude,longitude:m.location.longitude}}else{ext=c(m.text??m.caption??"",3000);a={summary:ext,source:"nota_supervisor"}}const {data:e,error}=await db.from("project_evidence").insert({workspace_id:l.workspace_id,project_id:pid,inbox_id:iid,visit_session_id:sid,evidence_type:t,extracted_text:ext,analysis:a,created_by:l.user_id,verification_status:t==="location"?"verified":"needs_verification",source_kind:"telegram"}).select("id").single();if(error)throw error;await db.from("assistant_inbox").update({project_id:pid,status:"processed",processed_at:new Date().toISOString(),processing_started_at:null}).eq("id",iid);return e}

async function startVisit(l:any,chat:any,p:any){const {data:old}=await db.from("assistant_visit_sessions").select("id").eq("telegram_link_id",l.id).eq("status","active").maybeSingle();if(old){await send(chat,"Ya hay una visita activa. Finalízala o cancélala antes de iniciar otra.");return}const {data:s,error}=await db.from("assistant_visit_sessions").insert({workspace_id:l.workspace_id,telegram_link_id:l.id,user_id:l.user_id,project_id:p.project_id,status:"active",title:`Visita · ${p.code||p.name}`}).select("id").single();if(error)throw error;await db.from("telegram_links").update({current_project_id:p.project_id,updated_at:new Date().toISOString()}).eq("id",l.id);l.current_project_id=p.project_id;linkCache.set(String(l.telegram_user_id||""),{at:0,v:l});await send(chat,`🟢 VISITA INICIADA\n\n📌 ${line(p)}\n\nEnvía fotos, audios, documentos, ubicación y notas. Te confirmaré cada recepción de inmediato.`)}
function fallbackVisit(evs:any[]){const notes:string[]=[],obs:string[]=[],rec:string[]=[],risks:string[]=[],facts:string[]=[],needs:string[]=[];for(const e of evs){if(e.extracted_text)notes.push(c(e.extracted_text,800));const a=e.analysis||{};for(const x of a.observations||[])obs.push(c(x,500));for(const x of a.recommendations||[])rec.push(c(x,500));for(const x of a.risks||[])risks.push(c(x,500));for(const x of a.facts||[])facts.push(c(x,500));for(const x of a.needs_verification||[])needs.push(c(x,500))}return{visit_date:day(),objective:"Registrar y verificar las condiciones observadas durante la visita de supervisión.",activities:notes.join(" ").slice(0,3500),generalObservations:[...new Set(obs)].join(" ").slice(0,3500)||notes.join(" ").slice(0,2500),instructions:[...new Set(rec)].join(" ").slice(0,3000),summary:notes.slice(0,3).join(" ").slice(0,1200),weather:"",personnel:"",physicalProgress:null,risks:[...new Set(risks)],verifiedFacts:[...new Set(facts)],needsVerification:[...new Set(needs)]}}
async function closeVisit(l:any,s:any,chat:any){try{const {data:p}=await db.from("projects").select("code,name").eq("id",s.project_id).single();let {data:e}=await db.from("project_evidence").select("id,evidence_type,extracted_text,analysis,verification_status").eq("visit_session_id",s.id).order("created_at");const evs=e||[],compact=evs.slice(0,40).map((x:any)=>({type:x.evidence_type,text:c(x.extracted_text,900),analysis:x.analysis}));let a:any;try{a=pj(out(await gem(`Consolida una visita de supervisión para ${p.code} · ${p.name} usando SOLO esta evidencia: ${JSON.stringify(compact).slice(0,18000)}. Devuelve SOLO JSON {"visit_date":"YYYY-MM-DD","objective":"","activities":"","generalObservations":"","instructions":"","summary":"","weather":"","personnel":"","physicalProgress":null,"risks":[],"verifiedFacts":[],"needsVerification":[]}. No inventes datos.`,FAST)))}catch{}if(!a)a=fallbackVisit(evs);a.visit_date=/^\d{4}-\d{2}-\d{2}$/.test(a.visit_date||"")?a.visit_date:day();a.evidenceIds=evs.map((x:any)=>x.id);a.visitSessionId=s.id;const {data:d,error}=await db.from("assistant_drafts").insert({workspace_id:l.workspace_id,project_id:s.project_id,draft_type:"visit",title:`Visita · ${p.code}`,summary:a.summary||"Borrador de visita",parsed_data:a,status:"draft",created_by:l.user_id}).select("id").single();if(error)throw error;await db.from("assistant_visit_sessions").update({status:"review",summary:a.summary||null,metadata:{draft_id:d.id,evidence_count:evs.length},updated_at:new Date().toISOString()}).eq("id",s.id);await send(chat,`🧠 BORRADOR DE VISITA\n\n📌 ${p.code} · ${cleanProjectName(p)}\n📎 Evidencias: ${evs.length}\n\nACTIVIDADES\n${c(a.activities,750)||"Sin detalle"}\n\nOBSERVACIONES\n${c(a.generalObservations,1000)||"Sin observaciones"}\n\nINSTRUCCIONES\n${c(a.instructions,750)||"Sin instrucciones"}`,{inline_keyboard:[[{text:"✅ Registrar",callback_data:`vap:${d.id}`},{text:"✅📄 Registrar + informe",callback_data:`vair:${d.id}`}],[{text:"❌ Cancelar",callback_data:`vrej:${d.id}`}]]})}catch(err){await send(chat,`No pude cerrar la visita: ${c(err instanceof Error?err.message:err,500)}`)}}
async function applyVisit(l:any,id:string,chat:any,withReport=false){const {data:d}=await db.from("assistant_drafts").select("*").eq("id",id).eq("workspace_id",l.workspace_id).maybeSingle();if(!d||d.status==="applied"){await send(chat,"Ese borrador ya fue aplicado o no existe.");return}const a=d.parsed_data||{}, {data:last}=await db.from("visits").select("visit_number").eq("project_id",d.project_id).is("voided_at",null).order("visit_number",{ascending:false}).limit(1).maybeSingle(),n=(Number(last?.visit_number)||0)+1,vid=crypto.randomUUID();const raw={id:vid,projectId:d.project_id,number:n,date:a.visit_date||day(),type:"Supervisión",status:"En seguimiento",objective:a.objective||"",activities:a.activities||"",generalObservations:a.generalObservations||a.summary||"",instructions:a.instructions||"",summary:a.summary||"",weather:a.weather||"No registrado",personnel:a.personnel||"No registrado",physicalProgress:a.physicalProgress??null,risks:a.risks||[],verifiedFacts:a.verifiedFacts||[],needsVerification:a.needsVerification||[],evidenceIds:a.evidenceIds||[],visitSessionId:a.visitSessionId||null,source:"Telegram · Ingeniero Móvil"};const {error}=await db.from("visits").insert({id:vid,workspace_id:l.workspace_id,project_id:d.project_id,visit_number:n,visit_date:raw.date,summary:raw.summary||raw.generalObservations,raw_data:raw});if(error)throw error;if(a.evidenceIds?.length)await db.from("project_evidence").update({visit_id:vid,source_kind:"visit"}).in("id",a.evidenceIds);await db.from("assistant_drafts").update({status:"applied",approved_by:l.user_id,approved_at:new Date().toISOString(),applied_at:new Date().toISOString()}).eq("id",id);if(a.visitSessionId)await db.from("assistant_visit_sessions").update({status:"closed",ended_at:new Date().toISOString()}).eq("id",a.visitSessionId);await send(chat,`✅ Visita N.º ${n} registrada.`,{inline_keyboard:[[{text:"↩️ Deshacer (15 min)",callback_data:`vundo:${vid}`}]]});if(withReport){const {data:r}=await db.from("assistant_drafts").insert({workspace_id:l.workspace_id,project_id:d.project_id,draft_type:"generate_report",title:`VISITA DE SUPERVISIÓN N.º ${n}`,source_text:`Genera informe de visita ${n}`,summary:"Informe de visita",parsed_data:{report_type:"visitas",evidence_ids:a.evidenceIds||[],request_text:`Genera informe de visita ${n}`,visit_selection:String(n)},status:"draft",created_by:l.user_id}).select("id").single();await send(chat,"📄 Elige formato:",formatKB(r.id))}}

async function handleVisitCallback(u:any,l:any,r:any,chat:any){const d=c(u.callback_query.data,100),[a,id]=d.split(":");if(!["vap","vair","vrej","vundo"].includes(a))return false;try{await tg("answerCallbackQuery",{callback_query_id:u.callback_query.id,text:"Procesando..."})}catch{}if(a==="vrej"){await db.from("assistant_drafts").update({status:"rejected"}).eq("id",id).eq("workspace_id",l.workspace_id);await send(chat,"❌ Borrador descartado.");return true}if(!VISIT_WRITE.has(r.role)){await send(chat,"Tu rol no permite esta acción.");return true}if(a==="vap"||a==="vair"){await applyVisit(l,id,chat,a==="vair");return true}if(a==="vundo"){const {data:v}=await db.from("visits").select("created_at,voided_at").eq("id",id).eq("workspace_id",l.workspace_id).maybeSingle();if(v&&!v.voided_at&&Date.now()-new Date(v.created_at).getTime()<=900000){await db.from("visits").update({voided_at:new Date().toISOString(),voided_by:l.user_id,void_reason:"Deshacer desde Telegram"}).eq("id",id);await send(chat,"↩️ Visita anulada con trazabilidad.")}else await send(chat,"El plazo para deshacer ya venció.");return true}return false}
async function handleStatusCallback(u:any,l:any,r:any,chat:any){const d=c(u.callback_query?.data,100);if(!d.startsWith("st:"))return false;try{await tg("answerCallbackQuery",{callback_query_id:u.callback_query.id,text:"Listo"})}catch{}const s=await session(l.id);if(d==="st:project"){const p=l.current_project_id?await resolveProject(l,"",true):null;if(!p){await send(chat,"No hay un proyecto activo. Usa /usar <proyecto>.");return true}const z=await snap(l,p.project_id),co=z?.contract||{},amount=co.original_amount??z?.project?.budget_estimate??p.budget_estimate;await send(chat,["📋 PROYECTO ACTIVO",`📌 ${p.code||""} · ${cleanProjectName(p)}`,`Estado: ${z?.project?.status||p.status||"No registrado"}`,`Monto contratado: ${amount!=null?money(amount):"No registrado"}`,`Contratista: ${co.contractor||"No registrado"}`,`Plazo: ${co.execution_days??z?.project?.execution_days??"No registrado"} días`,`Finalización: ${dateHN(co.end_date||z?.project?.end_date)}`,`Visitas registradas: ${z?.visit_count||0}`].join("\n"));return true}if(d==="st:visit"){if(!s){await send(chat,"📸 No hay una visita activa o pendiente de revisión.");return true}const {count}=await db.from("project_evidence").select("id",{head:true,count:"exact"}).eq("visit_session_id",s.id);const {data:p}=await db.from("projects").select("code,name").eq("id",s.project_id).maybeSingle();const state=s.status==="active"?"Activa":"En revisión";await send(chat,`📸 VISITA ACTUAL\n📌 ${p?.code||"Proyecto"} · ${p?cleanProjectName(p):""}\nEstado: ${state}\nEvidencias: ${count||0}\nInicio: ${dateHN(s.created_at)}`);return true}if(d==="st:report"){const p=l.current_project_id?await resolveProject(l,"",true):null;if(!p){await send(chat,"No hay un proyecto activo para generar el informe.");return true}await typing(chat);await reportStart(l,chat,`Genera informe general ${p.code||p.name}`);return true}if(d==="st:close"){if(!s||s.status!=="active"){await send(chat,"No hay una visita activa para finalizar.");return true}if(!VISIT_WRITE.has(r.role)){await send(chat,"Tu rol no permite finalizar visitas.");return true}await send(chat,"⚡ Visita recibida. Estoy consolidando la evidencia y preparando el borrador...");EdgeRuntime.waitUntil(closeVisit(l,s,chat));return true}return true}

Deno.serve(async req=>{const t0=Date.now();try{if(req.method==="GET")return j({ok:true,service:"telegram-gateway",version:"4.1-compact-status",fast_model:FAST,heavy_model:HEAVY});if(req.method!=="POST")return j({error:"method"},405);if((req.headers.get("x-telegram-bot-api-secret-token")??"")!==await h(T))return j({error:"unauthorized"},401);const u=await req.json(),m=u?.message??u?.edited_message??u?.callback_query?.message,f=u?.message?.from??u?.edited_message?.from??u?.callback_query?.from,chat=m?.chat?.id,tid=f?.id;if(!chat||!tid)return j({ok:true});const l=await link(tid);if(!l){const z=await core(u);return j({ok:z.ok,delegated:true})}const r=await role(l);if(!r){await send(chat,"Tu acceso a Control Contractual no está activo.");return j({ok:false})}
if(u.callback_query){if(await handleStatusCallback(u,l,r,chat))return j({ok:true,status_action:true,ms:Date.now()-t0});if(await handleVisitCallback(u,l,r,chat))return j({ok:true,ms:Date.now()-t0});EdgeRuntime.waitUntil(core(u).catch(()=>null));return j({ok:true,delegated:true,ms:Date.now()-t0})}
const text=c(m.text??m.caption??"",3000),n=nm(text),cmd=(text.split(/\s+/)[0]||"").toLowerCase();const s=await session(l.id);
if(cmd==="/start"){await send(chat,"✅ Ingeniero Móvil activo. Consultas simples responden directo; fotos y audios se analizan en segundo plano.\n\n/usar <proyecto> · /visita <proyecto> · /actual · /estado");return j({ok:true,ms:Date.now()-t0})}
if(cmd==="/actual"||cmd==="/estado"){const p=l.current_project_id?await resolveProject(l,"",true):null;const visit=s?.status==="active"?"Activa":s?.status==="review"?"En revisión":"No";const msg=p?`📌 ${p.code||"PROYECTO ACTIVO"}\n${cleanProjectName(p)}\n🏗️ Visita: ${visit} · 👤 ${roleLabel(r.role)}`:`📌 Sin proyecto activo\n🏗️ Visita: ${visit} · 👤 ${roleLabel(r.role)}\nUsa /usar <proyecto> para seleccionarlo.`;await send(chat,msg,statusKB(s?.status==="active"));return j({ok:true,compact_status:true,ms:Date.now()-t0})}
if(cmd==="/usar"){const q=text.replace(/^\/usar\s*/i,"").trim(),rows=await search(l.workspace_id,q,5),p=pick(rows);if(!p){await send(chat,`No pude identificar un único proyecto.${rows.length?`\n\n${rows.map(line).join("\n")}`:""}`);return j({ok:true})}await db.from("telegram_links").update({current_project_id:p.project_id,updated_at:new Date().toISOString()}).eq("id",l.id);l.current_project_id=p.project_id;linkCache.set(String(tid),{at:Date.now(),v:l});await send(chat,`📌 Proyecto activo:\n${line(p)}`);return j({ok:true,ms:Date.now()-t0})}
if(cmd==="/proyectos"){const q=text.replace(/^\/proyectos\s*/i,"").trim();if(q){const rows=await search(l.workspace_id,q,20);await send(chat,rows.length?`🏗️ Coincidencias:\n\n${rows.map((x:any,i:number)=>`${i+1}. ${line(x)}`).join("\n")}`:"Sin coincidencias.")}else{const {data}=await db.from("projects").select("code,name,status").eq("workspace_id",l.workspace_id).is("archived_at",null).order("name");await send(chat,`🏗️ Proyectos: ${data?.length||0}\n\n${(data||[]).slice(0,80).map((x:any,i:number)=>`${i+1}. ${line(x)} — ${x.status||""}`).join("\n")}`)}return j({ok:true,ms:Date.now()-t0})}
if(cmd==="/visita"||/\b(iniciar|comenzar|nueva) visita\b/.test(n)){if(!VISIT_WRITE.has(r.role)){await send(chat,"No tienes permiso para registrar visitas.");return j({ok:false})}const q=text.replace(/^\/visita\s*/i,"").replace(/\b(iniciar|comenzar|nueva) visita\b/ig,"").trim();const p=q?pick(await search(l.workspace_id,q,5)):l.current_project_id?await resolveProject(l,"",true):null;if(!p){await send(chat,"Usa /visita <nombre o código>.");return j({ok:true})}await startVisit(l,chat,p);return j({ok:true,ms:Date.now()-t0})}
if(s?.status==="active"&&(cmd==="/finalizar"||/\bfinalizar visita\b/.test(n))){await send(chat,"⚡ Visita recibida. Estoy consolidando la evidencia y preparando el borrador...");EdgeRuntime.waitUntil(closeVisit(l,s,chat));return j({ok:true,background:true,ms:Date.now()-t0})}
if(s?.status==="active"&&(cmd==="/cancelarvisita"||/\bcancelar visita\b/.test(n))){await db.from("assistant_visit_sessions").update({status:"cancelled",ended_at:new Date().toISOString()}).eq("id",s.id);await send(chat,"❌ Visita cancelada; la evidencia queda conservada.");return j({ok:true})}
if(s?.status==="active"&&type(m)==="text"&&isFact(text)){const p=await resolveProject(l,text,true);if(p){const s0=await snap(l,p.project_id);await send(chat,factReply(s0,text));return j({ok:true,fast_fact:true,during_visit:true,ms:Date.now()-t0})}}
if(s?.status==="active"){if(!VISIT_WRITE.has(r.role)){await send(chat,"Tu rol no permite agregar evidencia.");return j({ok:false})}if(["photo","voice","audio","document"].includes(type(m))){const e=await queueMedia(l,u,m,s.project_id,s.id);const ic=type(m)==="photo"?"📷":/voice|audio/.test(type(m))?"🎤":"📄";const {count}=await db.from("project_evidence").select("id",{head:true,count:"exact"}).eq("visit_session_id",s.id);await send(chat,`${ic} Recibido. Evidencias acumuladas: ${count||1}. El análisis continúa en segundo plano.`);return j({ok:true,background:true,evidence:e.id,ms:Date.now()-t0})}const e=await addQuickEvidence(l,u,m,s.project_id,s.id);await send(chat,`${type(m)==="location"?"📍":"📝"} Recibido.`);return j({ok:true,evidence:e.id,ms:Date.now()-t0})}
if(["photo","voice","audio","document"].includes(type(m))){const pid=l.current_project_id||null,e=await queueMedia(l,u,m,pid,null);await send(chat,pid?`${type(m)==="photo"?"📷":/voice|audio/.test(type(m))?"🎤":"📄"} Archivo recibido. Ya quedó guardado para el proyecto activo; lo analizo en segundo plano.`:"📥 Archivo guardado sin asignar. Usa /usar <proyecto> para definir el expediente antes de utilizarlo en un informe.");return j({ok:true,background:true,evidence:e.id,ms:Date.now()-t0})}
if(type(m)==="location"){if(!l.current_project_id){await send(chat,"📍 Ubicación recibida. Selecciona primero /usar <proyecto> para asociarla.");return j({ok:true})}await addQuickEvidence(l,u,m,l.current_project_id,null);await send(chat,"📍 Ubicación guardada.");return j({ok:true,ms:Date.now()-t0})}
if(!text)return j({ok:true});
if(isReport(text)){await typing(chat);await reportStart(l,chat,text);return j({ok:true,fast_report:true,ms:Date.now()-t0})}
if(isFact(text)){const p=await resolveProject(l,text,true);if(p){const s0=await snap(l,p.project_id);await send(chat,factReply(s0,text));return j({ok:true,fast_fact:true,ms:Date.now()-t0})}}
await typing(chat);const p=await resolveProject(l,text,false);let context="";if(p){const s0=await snap(l,p.project_id);context=`Proyecto identificado: ${JSON.stringify(s0)}`;}else if(l.current_project_id&&/\b(este|esta|actual|proyecto)\b/.test(n)){const s0=await snap(l,l.current_project_id);context=`Proyecto activo: ${JSON.stringify(s0)}`;}const task=(async()=>{try{const prompt=`Eres el Ingeniero Móvil de Control Contractual. Responde en español, claro, práctico y profesional. Usa los datos del expediente como verdad y no inventes. ${context}\nPregunta: ${text}`;const reply=c(out(await gem(prompt,FAST)),3900)||"No pude completar la consulta.";await send(chat,reply)}catch(err){await send(chat,`No pude completar la consulta: ${c(err instanceof Error?err.message:err,500)}`)}})();EdgeRuntime.waitUntil(task);return j({ok:true,background_chat:true,ms:Date.now()-t0})
}catch(err){console.error("gateway",err);return j({ok:false,error:c(err instanceof Error?err.message:err,600),ms:Date.now()-t0},500)}});