(()=>{'use strict';
const R=window.RM;if(!R)return;const $=R.$,$$=R.$$;
let processing=false;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function status(text,kind='info'){const n=$('#autoProcessStatus');if(!n)return;n.className=`notice ${kind}`;n.innerHTML=text;n.classList.remove('hidden')}
function autoTitle(){const d=new Date();return`Reunión ${new Intl.DateTimeFormat('es-HN',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(d)}`}
async function waitForAi(){for(let i=0;i<25;i++){if(typeof R.transcribeMeetingAudio==='function')return true;await sleep(300)}return false}
function resetRecord(){['meetingTitle','meetingProject','meetingParticipants','meetingTranscript','meetingNotes'].forEach(id=>{const el=$('#'+id);if(el)el.value=''});if($('#meetingDate'))$('#meetingDate').value=R.iso(new Date());if($('#analysisResults'))$('#analysisResults').classList.add('hidden');if($('#audioBox'))$('#audioBox').classList.add('hidden');R.audioBlob=null;R.lastAnalysis=null;R.detected=[];R.secs=0;if($('#timer'))$('#timer').textContent='00:00:00'}
R.quickSaveAndProcess=async()=>{if(processing||!R.audioBlob)return;processing=true;const blob=R.audioBlob,id=R.uid(),date=$('#meetingDate')?.value||R.iso(new Date()),title=$('#meetingTitle')?.value.trim()||autoTitle(),summaryType=$('#summaryType')?.value||'executive',summaryDetail=$('#summaryDetail')?.value||'medium';status('<b>💾 Guardando reunión…</b> La app hará el resto automáticamente.');try{await R.putAudio?.(id,blob);R.meetings.push({id,title,project:$('#meetingProject')?.value.trim()||'',participants:$('#meetingParticipants')?.value.trim()||'',meetingDate:date,transcript:$('#meetingTranscript')?.value.trim()||'',notes:$('#meetingNotes')?.value.trim()||'',summary:'Procesando grabación…',summaryType,summaryDetail,analysis:{processing:true},audioSize:blob.size,audioMime:blob.type||'audio/webm',duration:R.secs,createdAt:new Date().toISOString()});R.save();R.dashboard();R.renderMeetings();if(!R.cloudUser){status('<b>✓ Reunión guardada en el teléfono.</b><br>Cuando inicies sesión, podrá sincronizarse y analizarse con IA.','good');resetRecord();return}status('<b>☁️ Subiendo grabación…</b>');await R.cloudSyncNow?.();const ready=await waitForAi();if(!ready)throw new Error('El módulo de análisis todavía no está listo. La reunión quedó guardada y podrás procesarla desde Historial.');const data=await R.transcribeMeetingAudio(id,null,{silent:true,onStatus:t=>status(`<b>${t}</b>`)});status(`<b>✓ Análisis terminado.</b><br>${data?.tasks_created||0} asignación(es) nuevas. Abriendo la información extraída…`,'good');resetRecord();setTimeout(()=>R.go('meetings'),650)}catch(e){console.error(e);status(`<b>La reunión quedó guardada.</b><br>${R.esc(e?.message||'No se pudo completar el análisis automático. Puedes reintentarlo desde Historial.')}`,'bad');resetRecord()}finally{processing=false}};
function listBlock(title,items){if(!Array.isArray(items)||!items.length)return'';return`<div class="extractBlock"><b>${R.esc(title)}</b><ul>${items.map(x=>`<li>${R.esc(typeof x==='string'?x:(x?.title||JSON.stringify(x)))}</li>`).join('')}</ul></div>`}
function textBlock(title,text){if(!text)return'';return`<div class="extractBlock full"><b>${R.esc(title)}</b><p class="transcriptText">${R.esc(text)}</p></div>`}
function enrichMeetings(){const cards=$$('#meetingList .meetingCard'),sorted=[...R.meetings].sort((a,b)=>b.createdAt.localeCompare(a.createdAt));cards.forEach((card,i)=>{if(card.querySelector('.extractedPanel'))return;const m=sorted[i];if(!m)return;const a=m.analysis||{},tasks=R.tasks.filter(t=>t.meetingId===m.id);const panel=document.createElement('details');panel.className='extractedPanel';panel.open=i===0&&!!m.transcript;panel.innerHTML=`<summary>📋 Ver toda la información extraída</summary><div class="extractGrid">${textBlock('Conclusión ejecutiva',a.executive_conclusion)}${listBlock('Temas',a.topics)}${listBlock('Participantes identificables',a.participants)}${listBlock('Instituciones / empresas',a.organizations)}${listBlock('Lugares',a.places)}${listBlock('Acuerdos',a.agreements)}${listBlock('Decisiones',a.decisions)}${listBlock('Problemas / observaciones',a.problems)}${listBlock('Riesgos',a.risks)}${listBlock('Montos',a.amounts)}${listBlock('Documentos mencionados',a.documents)}${listBlock('Fechas mencionadas',a.dates_mentioned)}${listBlock('Preguntas pendientes',a.open_questions)}${listBlock('Datos clave',a.key_facts)}${listBlock('Asignaciones',tasks.map(t=>`${t.title} — ${t.owner||'Sin responsable'}${t.date?' — '+R.fmt(t.date):' — Sin fecha'}`))}${m.transcript?textBlock('Transcripción completa',m.transcript):''}</div>`;card.appendChild(panel)})}
const baseRender=R.renderMeetings;R.renderMeetings=()=>{baseRender();enrichMeetings()};
const baseGo=R.go;R.go=id=>{baseGo(id);if(id==='meetings')setTimeout(enrichMeetings,0)};
setInterval(()=>{if(document.querySelector('#meetings.view.active'))enrichMeetings()},1800);
})();