(()=>{'use strict';
const R=window.RM;if(!R)return;const $=R.$;
const SUPABASE_URL='https://flethujkrharehjikwgj.supabase.co';
const SUPABASE_KEY='sb_publishable_UqstbAXxbwLd8NqeiyEQrA_IOESNT-6';
let client=null,user=null,cloudReady=false,syncing=false,syncTimer=null;const audioPaths=new Map();
const originalSave=R.save,localGetAudio=R.getAudio,localDelAudio=R.delAudio;
const uuid=()=>crypto.randomUUID();
const isUuid=s=>/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(String(s||''));
function ensureIds(){const remap=new Map();R.meetings.forEach(m=>{if(!isUuid(m.id)){const old=m.id;m.id=uuid();remap.set(old,m.id)}});R.tasks.forEach(t=>{if(!isUuid(t.id))t.id=uuid();if(t.meetingId&&remap.has(t.meetingId))t.meetingId=remap.get(t.meetingId)})}
function setStatus(text,kind='info'){const n=$('#cloudStatus');if(n){n.className=`notice ${kind}`;n.innerHTML=text}const b=$('#cloudBadge');if(b){b.textContent=kind==='good'?'☁️ Sincronizado':kind==='bad'?'☁️ Sin conexión':'☁️ '+text.replace(/<[^>]+>/g,'').slice(0,18)}}
function meetingRow(m){return{id:m.id,user_id:user.id,title:m.title||'Reunión',project_name:m.project||'',transcript:m.transcript||'',notes:m.notes||'',summary_type:m.summaryType||'executive',summary_level:m.summaryDetail||'medium',summary_text:m.summary||'',analysis:{...(m.analysis||{}),participants:m.participants||m.analysis?.participants||[]},audio_path:m.audioPath||audioPaths.get(m.id)||null,audio_mime:m.audioMime||'',audio_size:Number(m.audioSize||0),duration_seconds:Number(m.duration||0),meeting_date:m.meetingDate?new Date(m.meetingDate+'T12:00:00').toISOString():(m.createdAt||new Date().toISOString()),created_at:m.createdAt||new Date().toISOString(),updated_at:new Date().toISOString()}}
function meetingLocal(x){if(x.audio_path)audioPaths.set(x.id,x.audio_path);const p=x.analysis?.participants;return{id:x.id,title:x.title,project:x.project_name||'',participants:Array.isArray(p)?p.join(', '):(p||''),meetingDate:(x.meeting_date||x.created_at||'').slice(0,10),transcript:x.transcript||'',notes:x.notes||'',summary:x.summary_text||'',summaryType:x.summary_type||'executive',summaryDetail:x.summary_level||'medium',analysis:x.analysis||{},audioPath:x.audio_path||'',audioMime:x.audio_mime||'',audioSize:Number(x.audio_size||0),duration:Number(x.duration_seconds||0),createdAt:x.created_at||new Date().toISOString()}}
function taskRow(t){return{id:t.id,user_id:user.id,meeting_id:isUuid(t.meetingId)?t.meetingId:null,title:t.title||'Actividad',responsible:t.owner||'',due_date:t.date||null,due_time:t.time||null,priority:['Alta','Normal','Baja'].includes(t.priority)?t.priority:'Normal',status:['Pendiente','En proceso','Completada'].includes(t.status)?t.status:'Pendiente',source_text:t.sourceText||t.sourceMeetingTitle||'',updated_at:new Date().toISOString()}}
function taskLocal(x){return{id:x.id,meetingId:x.meeting_id||null,title:x.title,owner:x.responsible||'',date:x.due_date||'',time:(x.due_time||'').slice(0,5),priority:x.priority||'Normal',status:x.status||'Pendiente',sourceText:x.source_text||'',sourceMeetingTitle:x.source_text||''}}
function mergeById(local,remote){const m=new Map(local.map(x=>[x.id,x]));remote.forEach(x=>m.set(x.id,{...(m.get(x.id)||{}),...x}));return[...m.values()]}
async function uploadMissingAudio(){for(const m of R.meetings){if(!m.audioSize||m.audioPath||audioPaths.get(m.id))continue;let blob=null;try{blob=await localGetAudio?.(m.id)}catch{}if(!blob)continue;const ext=blob.type.includes('ogg')?'ogg':blob.type.includes('mp4')?'m4a':blob.type.includes('mpeg')?'mp3':blob.type.includes('wav')?'wav':'webm';const path=`${user.id}/${m.id}.${ext}`;const {error}=await client.storage.from('meeting-audio').upload(path,blob,{contentType:blob.type||'audio/webm',upsert:true});if(!error){m.audioPath=path;m.audioMime=blob.type||'';audioPaths.set(m.id,path)}}}
async function deleteMissing(table,remoteIds,localIds){const missing=remoteIds.filter(id=>!localIds.has(id));if(missing.length)await client.from(table).delete().in('id',missing)}
async function syncAll(){if(!user||!cloudReady||syncing)return;syncing=true;setStatus('<b>☁️ Sincronizando…</b>','info');try{ensureIds();await uploadMissingAudio();const mr=R.meetings.map(meetingRow),tr=R.tasks.map(taskRow);if(mr.length){const {error}=await client.from('meeting_records').upsert(mr,{onConflict:'id'});if(error)throw error}if(tr.length){const {error}=await client.from('meeting_tasks').upsert(tr,{onConflict:'id'});if(error)throw error}const [{data:remoteM,error:em},{data:remoteT,error:et}]=await Promise.all([client.from('meeting_records').select('id'),client.from('meeting_tasks').select('id')]);if(em)throw em;if(et)throw et;await deleteMissing('meeting_records',(remoteM||[]).map(x=>x.id),new Set(R.meetings.map(x=>x.id)));await deleteMissing('meeting_tasks',(remoteT||[]).map(x=>x.id),new Set(R.tasks.map(x=>x.id)));originalSave();setStatus(`<b>✓ Sincronizado.</b> ${R.meetings.length} reuniones y ${R.tasks.length} tareas disponibles en tu cuenta.`,'good')}catch(e){console.error('cloud sync',e);setStatus('<b>No se pudo sincronizar.</b> Tus datos siguen guardados en este dispositivo y se intentará nuevamente cuando haya conexión.','bad')}finally{syncing=false}}
function queueSync(){clearTimeout(syncTimer);syncTimer=setTimeout(syncAll,500)}
R.cloudSyncNow=syncAll;
R.save=()=>{originalSave();if(user&&cloudReady)queueSync()};
R.getAudio=async id=>{try{const b=await localGetAudio?.(id);if(b)return b}catch{}if(!user)return null;const path=audioPaths.get(id)||R.meetings.find(m=>m.id===id)?.audioPath;if(!path)return null;const {data,error}=await client.storage.from('meeting-audio').download(path);if(error)return null;try{await R.putAudio?.(id,data)}catch{}return data};
R.delAudio=async id=>{try{await localDelAudio?.(id)}catch{}const path=audioPaths.get(id);if(user&&path){await client.storage.from('meeting-audio').remove([path]);audioPaths.delete(id)}};
async function loadCloud(){if(!user)return;setStatus('<b>☁️ Cargando tu cuenta…</b>','info');try{ensureIds();const [{data:m,error:em},{data:t,error:et}]=await Promise.all([client.from('meeting_records').select('*').order('meeting_date',{ascending:false}),client.from('meeting_tasks').select('*').order('due_date',{ascending:true})]);if(em)throw em;if(et)throw et;R.meetings=mergeById(R.meetings,(m||[]).map(meetingLocal));R.tasks=mergeById(R.tasks,(t||[]).map(taskLocal));originalSave();cloudReady=true;R.dashboard();R.renderCalendar();R.renderTasks();R.renderMeetings();await syncAll()}catch(e){console.error('cloud load',e);setStatus('<b>Error al cargar la nube.</b> La aplicación seguirá funcionando con los datos locales.','bad')}}
function authUi(){const out=$('#authLoggedOut'),inn=$('#authLoggedIn'),email=$('#authEmail');if(out)out.classList.toggle('hidden',!!user);if(inn)inn.classList.toggle('hidden',!user);if(email)email.textContent=user?.email||'';if(user){$('#profileEmailInput').value=user.email||R.profile.email||'';setStatus('<b>Cuenta conectada.</b> Cargando y sincronizando tus datos…','info')}else setStatus('<b>Modo local.</b> Inicia sesión para tener la misma información en cualquier celular o computadora.','info')}
async function setUser(u){user=u||null;R.cloudUser=user;cloudReady=false;authUi();if(user)await loadCloud()}
async function init(){if(!window.supabase?.createClient){setStatus('<b>Nube no disponible.</b> La aplicación continúa en modo local.','bad');return}client=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});R.supabase=client;const {data}=await client.auth.getSession();await setUser(data.session?.user||null);client.auth.onAuthStateChange((_e,s)=>{if((s?.user?.id||null)!==(user?.id||null))setUser(s?.user||null)});const login=$('#loginForm');if(login)login.onsubmit=async e=>{e.preventDefault();const email=$('#loginEmail').value.trim(),password=$('#loginPassword').value;if(!email||!password)return alert('Escribe correo y contraseña.');setStatus('<b>Iniciando sesión…</b>','info');const {error}=await client.auth.signInWithPassword({email,password});if(error)alert('No se pudo iniciar sesión: '+error.message)};const signup=$('#signupBtn');if(signup)signup.onclick=async()=>{const email=$('#loginEmail').value.trim(),password=$('#loginPassword').value;if(!email||password.length<6)return alert('Escribe un correo y una contraseña de al menos 6 caracteres.');const {error}=await client.auth.signUp({email,password});if(error)alert('No se pudo crear la cuenta: '+error.message);else alert('Cuenta creada. Si Supabase solicita confirmar el correo, revisa tu bandeja de entrada.')};const logout=$('#logoutBtn');if(logout)logout.onclick=async()=>{await client.auth.signOut();location.reload()};const sync=$('#syncNowBtn');if(sync)sync.onclick=()=>syncAll()}
init().catch(e=>{console.error(e);setStatus('<b>No se pudo iniciar la conexión con la nube.</b> Tus datos locales siguen disponibles.','bad')});
const ai=document.createElement('script');ai.src='./ai-audio-v5.js?v=6';ai.defer=true;document.head.appendChild(ai);
})();