import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.57.0";

const U=Deno.env.get("SUPABASE_URL")??"";
const K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??"";
const T=Deno.env.get("TELEGRAM_BOT_TOKEN")??"";
const G=Deno.env.get("GEMINI_API_KEY")??"";
const FAST=Deno.env.get("GEMINI_FAST_MODEL")??"gemini-3.5-flash-lite";
const db=createClient(U,K,{auth:{persistSession:false,autoRefreshToken:false}});
const GATEWAY=`${U}/functions/v1/telegram-gateway`;
const SANITIZER=`${U}/functions/v1/visit-image-sanitizer`;
const RELOADER=`${U}/functions/v1/visit-photo-reloader`;
const EXPORTER=`${U}/functions/v1/visit-report-exporter`;
const ZERO_ID="00000000-0000-0000-0000-000000000000";

const clean=(v:any,n=5000)=>String(v??"").replace(/[\u0000-\u001f\u007f]/g," ").trim().slice(0,n);
const norm=(v:any)=>String(v??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9ñº°]+/g," ").replace(/\s+/g," ").trim();
const json=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{"content-type":"application/json","cache-control":"no-store"}});
const dateHN=(v:any)=>{const s=String(v??""),m=s.match(/^(\d{4})-(\d{2})-(\d{2})/);return m?`${m[3]}/${m[2]}/${m[1]}`:(s||"No registrada")};
const money=(v:any)=>`L. ${Number(v||0).toLocaleString("es-HN",{minimumFractionDigits:2,maximumFractionDigits:2})}`;
async function sha(v:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return[...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function tg(method:string,body:any){const r=await fetch(`https://api.telegram.org/bot${T}/${method}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),d=await r.json().catch(()=>({}));if(!r.ok||d?.ok===false)throw new Error(d?.description||`Telegram ${r.status}`);return d}
const send=(chat:any,text:string,k?:any)=>tg("sendMessage",{chat_id:chat,text:clean(text,3900),disable_web_page_preview:true,...(k?{reply_markup:k}:{})});
function reEsc(v:string){return String(v||"").replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}
function cleanProjectName(p:any){let name=clean(p?.name||"Proyecto",260),code=clean(p?.code||"",80);if(code){const e=reEsc(code);name=name.replace(new RegExp(`(?:[\\s,·—–-]+)?${e}\\s*$`,"i"),"").replace(new RegExp(`^${e}(?:\\s*[·,:—–-]\\s*|\\s+)`,"i"),"").trim()}name=name.replace(/^CONSTRUCCI[ÓO]N DE\s+/i,"").replace(/\s+SANTA\s+MAR[IÍ]A\s*$/i,"").replace(/\s+HACIA\s+/ig," → ").toLowerCase().replace(/\bbo\.\s*/ig,"Bo. ").replace(/\s+/g," ").trim();return name?name.charAt(0).toUpperCase()+name.slice(1):"Proyecto"}

function wantsVisitList(t:string){const n=norm(t);return n==="visitas"||n==="mis visitas"||n==="historial de visitas"||/\b(muestra|muestrame|mostrar|lista|listar|ver|ensena|ensename|abre|abrir|dame)\b.*\bvisitas\b/.test(n)||/^visitas\b/.test(n)||/\bque visitas\b/.test(n)}
function requestedVisitNumber(t:string){const n=norm(t);let m=n.match(/\bvisita\s*(?:numero\s*|n\s*)?(\d+)\b/);if(m)return Number(m[1]);m=n.match(/^(?:muestra|muestrame|mostrar|ver|abre|abrir|ensena|ensename|dame)\s+(?:la\s+)?(?:numero\s+|n\s+)?(\d+)\b/);return m?Number(m[1]):null}
function wantsLastVisit(t:string){return /\b(ultima|ultimo)\s+visita\b/.test(norm(t))}
function wantsReport(t:string){const n=norm(t);if(!/\b(informe|informes|reporte|reportes|documento|documentos|acta|actas)\b/.test(n))return false;if(/\b(visita|visitas|supervision|campo|financier|contractual|contrato|estimacion|pago|garantia|adjudic|oferta|recepcion|liquidacion|integral|completo)\b/.test(n))return true;return /^(informe|informes|reporte|reportes|documento|documentos|acta|actas)\b/.test(n)}
function reportType(t:string){const n=norm(t);if(/visita|supervision|campo/.test(n))return"visitas";if(/financier/.test(n))return"financiero";if(/contractual|contrato/.test(n))return"contractual";if(/estimacion|pago/.test(n))return"estimaciones";if(/garantia/.test(n))return"garantias";if(/adjudic|oferta|cierre/.test(n))return"adjudicacion";if(/recepcion/.test(n))return"recepcion";if(/liquidacion/.test(n))return"liquidacion";if(/integral|completo/.test(n))return"integral";return"general"}
function desiredFormat(t:string){const n=norm(t);if(/pdf\s*(y|\+|mas)\s*word|word\s*(y|\+|mas)\s*pdf|ambos|los dos|dos formatos/.test(n))return"both";if(/\bword\b|\bdocx\b/.test(n))return"docx";if(/\bpdf\b/.test(n))return"pdf";return null}
function wantsActiveVisit(t:string){const n=norm(t);return /\b(visita actual|visita activa|visita en curso|que visita tengo|cual visita tengo)\b/.test(n)}
function wantsSelectProject(t:string){const n=norm(t);return /^(usar|usa|selecciona|seleccionar|cambia|cambiar|cambiate|activar|activa)\b.*\b(proyecto|a|al)?\b/.test(n)&&!/\bvisita\b/.test(n)}
function wantsProjectInfo(t:string){const n=norm(t);return /\b(ver proyecto|proyecto actual|estado del proyecto|estado proyecto|monto contratado|contratista|plazo|finalizacion|firma|anticipo|pagos|estimaciones|garantias|garantia)\b/.test(n)||/^estado\b/.test(n)}
function isFinishVisit(t:string){return /\b(finaliza|finalizar|termina|terminar|cierra|cerrar)\b.*\bvisita\b/.test(norm(t))}
function isCancelVisit(t:string){return /\b(cancela|cancelar|descarta|descartar)\b.*\bvisita\b/.test(norm(t))}
function isStartVisit(t:string){return /\b(inicia|iniciar|comienza|comenzar|nueva|abre|abrir)\b.*\bvisita\b/.test(norm(t))}
function actionLike(t:string){const n=norm(t);return /^(muestra|muestrame|dime|dame|consulta|consultar|busca|buscar|revisa|revisar|analiza|analizar|genera|generar|prepara|preparar|abre|abrir|crea|crear|lista|listar|quiero|necesito|cual|cuanto|cuantos|como|ver|estado|informe|informes|visita|visitas|proyecto|monto|contratista|plazo|anticipo|pago|pagos|estimacion|estimaciones|garantia|garantias)\b/.test(n)}
function queryTerms(t:string){return clean(t,500).replace(/\b(genera|generar|crea|crear|prepara|preparar|haz|hacer|quiero|necesito|muestra|muestrame|mostrar|ver|dame|consulta|consultar|busca|buscar|revisa|revisar|analiza|analizar|usa|usar|selecciona|seleccionar|cambia|cambiar|cambiate|activar|activa|los|las|el|la|de|del|un|una|informe|informes|reporte|reportes|documento|documentos|acta|actas|visita|visitas|supervision|campo|proyecto|actual|activo|pdf|word|docx|ambos)\b/ig," ").replace(/\s+/g," ").trim()}

async function linkFor(tid:any){const {data}=await db.from("telegram_links").select("id,workspace_id,user_id,current_project_id,status").eq("telegram_user_id",tid).eq("status","active").limit(1).maybeSingle();if(!data)return null;const {data:member}=await db.from("workspace_members").select("workspace_id").eq("workspace_id",data.workspace_id).eq("user_id",data.user_id).eq("active",true).limit(1).maybeSingle();return member?data:null}
async function searchProjects(l:any,q:string,n=6){const {data,error}=await db.rpc("telegram_project_search",{p_workspace_id:l.workspace_id,p_query:q,p_limit:n});if(error)throw error;return data||[]}
function pick(rows:any[]){if(!rows.length)return null;const a=rows[0],b=rows[1],s=Number(a.match_score||0),s2=Number(b?.match_score||0);return s>=100||(s>=60&&(!b||s-s2>=18))?a:null}
async function getProject(l:any,id:string){const {data}=await db.from("projects").select("id,code,name,status,location,budget_estimate").eq("workspace_id",l.workspace_id).eq("id",id).is("archived_at",null).maybeSingle();return data}
async function activeSession(l:any){const {data}=await db.from("assistant_visit_sessions").select("id,project_id,status,created_at,updated_at").eq("telegram_link_id",l.id).in("status",["active","review"]).order("created_at",{ascending:false}).limit(1).maybeSingle();return data}
async function currentProject(l:any){let pid=l?.current_project_id||null;if(!pid){const s=await activeSession(l);pid=s?.project_id||null}return pid?getProject(l,pid):null}
async function resolveProject(l:any,text:string,allowCurrent=true){const q=queryTerms(text);if(q){const rows=await searchProjects(l,q,6),p=pick(rows);if(p){const x=await getProject(l,p.project_id);if(x)return x}if(rows.length===1){const x=await getProject(l,rows[0].project_id);if(x)return x}}return allowCurrent?currentProject(l):null}
async function visitsFor(l:any,p:any){const {data}=await db.from("visits").select("id,visit_number,visit_date,summary,raw_data").eq("workspace_id",l.workspace_id).eq("project_id",p.id).is("voided_at",null).order("visit_number",{ascending:true});return data||[]}
async function getVisit(l:any,p:any,num:number){const {data}=await db.from("visits").select("id,visit_number,visit_date,summary,raw_data").eq("workspace_id",l.workspace_id).eq("project_id",p.id).eq("visit_number",num).is("voided_at",null).maybeSingle();return data}
async function visitCount(sessionId:string){const {count}=await db.from("project_evidence").select("id",{head:true,count:"exact"}).eq("visit_session_id",sessionId);return count||0}
async function snapshot(l:any,pid:string){const {data,error}=await db.rpc("telegram_project_snapshot",{p_workspace_id:l.workspace_id,p_project_id:pid});if(error)throw error;return data}

function listKeyboard(p:any,rows:any[]){return{inline_keyboard:rows.map((v:any)=>[{text:`📍 Visita N.º ${v.visit_number} · ${dateHN(v.visit_date)}`,callback_data:`vqp:${p.id}:${v.visit_number}`}])}}
function summaryOf(v:any){const r=v?.raw_data||{};return clean(v?.summary||r?.summary||r?.generalObservations||r?.activities||"Sin resumen registrado.",360)}
async function showVisitListForProject(chat:any,l:any,p:any){const visits=await visitsFor(l,p),s=await activeSession(l),lines:string[]=[`📚 VISITAS · ${p.code||""}`,cleanProjectName(p),""];if(!visits.length)lines.push("No hay visitas registradas todavía.");else for(const v of visits)lines.push(`📍 N.º ${v.visit_number} · ${dateHN(v.visit_date)}\n${summaryOf(v)}`);if(s?.project_id===p.id)lines.push(`\n🟢 Visita actual: ${s.status==="active"?"Activa":"En revisión"} · ${await visitCount(s.id)} evidencias`);await send(chat,lines.join("\n\n"),visits.length?listKeyboard(p,visits):undefined)}
async function showVisitList(chat:any,l:any,text=""){const p=await resolveProject(l,text,true);if(!p){const q=queryTerms(text),rows=q?await searchProjects(l,q,5):[];await send(chat,rows.length?`No pude identificar un único proyecto.\n\n${rows.map((x:any)=>`• ${x.code||""} · ${x.name||""}`).join("\n")}`:"No hay un proyecto activo. Usa /usar <proyecto> para seleccionarlo.");return}await showVisitListForProject(chat,l,p)}
function invalidPhotoCount(v:any){const r=v?.raw_data||{},photos=Array.isArray(r.photos)?r.photos:[];return photos.filter((p:any)=>!String(p?.src||"").startsWith("data:image/")||String(p?.status||"").toLowerCase().includes("requiere")||!!p?.integrityError).length}
function detailText(v:any,p:any){const r=v?.raw_data||{},obs=Array.isArray(r.observations)?r.observations:[],lines:string[]=[`📍 VISITA N.º ${v.visit_number} · ${dateHN(v.visit_date)}`,`📌 ${p.code||""} · ${cleanProjectName(p)}`];if(r.status)lines.push(`Estado: ${r.status}`);if(r.objective)lines.push(`\n🎯 Objetivo\n${clean(r.objective,550)}`);if(r.activities)lines.push(`\n🏗️ Actividades\n${clean(r.activities,700)}`);const general=clean(v.summary||r.generalObservations||r.summary||"",900);if(general)lines.push(`\n📝 Observaciones\n${general}`);if(obs.length){lines.push(`\n⚠️ Observaciones registradas (${obs.length})`);for(const o of obs.slice(0,5))lines.push(`• ${clean(o?.text||o,330)}`)}if(r.instructions)lines.push(`\n📋 Instrucciones\n${clean(r.instructions,700)}`);if(r.commitments)lines.push(`\n🤝 Compromisos\n${clean(r.commitments,450)}`);const total=Number(r.photoCount??(Array.isArray(r.photos)?r.photos.length:0)??0);if(total)lines.push(`\n📷 Fotografías registradas: ${total}${r.reportPhotoCount!=null?` · válidas para informe: ${r.reportPhotoCount}`:""}`);if(r.photoIntegrityNote)lines.push(`⚠️ ${clean(r.photoIntegrityNote,350)}`);return clean(lines.join("\n"),3900)}
function visitDetailKeyboard(p:any,num:number,v?:any){const rows:any[]=[[{text:"📄 PDF",callback_data:`vrp:${p.id}:${num}:pdf`},{text:"📝 Word",callback_data:`vrp:${p.id}:${num}:docx`}],[{text:"📄📝 PDF + Word",callback_data:`vrp:${p.id}:${num}:both`}]];if(v&&invalidPhotoCount(v)>0)rows.push([{text:`🔄 Recargar fotografías (${invalidPhotoCount(v)})`,callback_data:`vrrp:${p.id}:${num}`}]);rows.push([{text:"📚 Ver todas las visitas",callback_data:`vqpl:${p.id}`}]);return{inline_keyboard:rows}}
async function internal(url:string,body:any){const r=await fetch(url,{method:"POST",headers:{"content-type":"application/json","x-internal-image-secret":await sha(T)},body:JSON.stringify(body)}),d=await r.json().catch(()=>({}));if(!r.ok||d?.ok===false)throw new Error(d?.error||`Servicio interno ${r.status}`);return d}
const sanitizeVisitImages=(visitId:string)=>internal(SANITIZER,{visit_id:visitId});
const reloadCall=(b:any)=>internal(RELOADER,b);
const exportVisitDraft=(l:any,draftId:string,fmt:string,chat:any)=>internal(EXPORTER,{link_id:l.id,draft_id:draftId,format:fmt,chat_id:chat});
async function showVisitForProject(chat:any,l:any,p:any,num:number){let v=await getVisit(l,p,num);if(!v){const all=await visitsFor(l,p);await send(chat,`No encontré la visita N.º ${num} en ${p.code||"este proyecto"}.${all.length?`\nVisitas disponibles: ${all.map((x:any)=>x.visit_number).join(", ")}.`:""}`);return}try{await sanitizeVisitImages(v.id);v=await getVisit(l,p,num)||v}catch{}await send(chat,detailText(v,p),visitDetailKeyboard(p,num,v))}
async function showVisit(chat:any,l:any,num:number,text=""){const p=await resolveProject(l,text,true);if(!p){await send(chat,"No pude identificar el proyecto.");return}await showVisitForProject(chat,l,p,num)}
async function evidenceIdsForVisit(l:any,p:any,visitId:string){const {data:e}=await db.from("project_evidence").select("id").eq("workspace_id",l.workspace_id).eq("project_id",p.id).eq("visit_id",visitId).order("created_at",{ascending:true});const ids=(e||[]).map((x:any)=>x.id);return ids.length?ids:[ZERO_ID]}
function formatKeyboard(draftId:string){return{inline_keyboard:[[{text:"📄 PDF",callback_data:`rf:${draftId}:pdf`},{text:"📝 Word",callback_data:`rf:${draftId}:docx`}],[{text:"📄📝 PDF + Word",callback_data:`rf:${draftId}:both`}],[{text:"❌ Cancelar",callback_data:`cancel:${draftId}`}]]}}
async function createVisitReportDraft(l:any,p:any,num:number){const v=await getVisit(l,p,num);if(!v)throw new Error(`No encontré la visita N.º ${num}.`);const ids=await evidenceIdsForVisit(l,p,v.id);const {data:d,error}=await db.from("assistant_drafts").insert({workspace_id:l.workspace_id,project_id:p.id,draft_type:"generate_report",title:`VISITA DE SUPERVISIÓN N.º ${num}`,source_text:`Genera informe de visita ${num}`,summary:`Informe de visita N.º ${num} desde Telegram`,parsed_data:{report_type:"visitas",evidence_ids:ids,request_text:`Genera informe de visita ${num}`,context_text:"",visit_selection:String(num)},status:"draft",created_by:l.user_id}).select("id").single();if(error)throw error;return d.id}
async function prepareVisitReport(chat:any,l:any,p:any,num:number,fmt:string|null){const v=await getVisit(l,p,num);if(!v){await send(chat,`No encontré la visita N.º ${num} de ${p.code||cleanProjectName(p)}.`);return}const check=await sanitizeVisitImages(v.id);if(Number(check.rejected||0)>0)await send(chat,`⚠️ Revisé las fotografías: ${check.valid||0} válida(s) y ${check.rejected||0} dañada(s). Las dañadas no se incluirán.`);const draftId=await createVisitReportDraft(l,p,num);if(fmt){await exportVisitDraft(l,draftId,fmt,chat);return}await send(chat,`📄 Informe de la Visita N.º ${num} preparado.\n📌 ${p.code||""} · ${cleanProjectName(p)}\n\n¿En qué formato?`,formatKeyboard(draftId))}
async function startNaturalReport(chat:any,l:any,text:string){const p=await resolveProject(l,text,true);if(!p){const q=queryTerms(text),rows=q?await searchProjects(l,q,5):[];await send(chat,rows.length?`No pude identificar un único proyecto. Elige uno o escribe su código:\n\n${rows.map((x:any)=>`• ${x.code||""} · ${x.name||""}`).join("\n")}`:"No pude identificar el proyecto para el informe.");return}const rt=reportType(text),fmt=desiredFormat(text);if(rt==="visitas"){const visits=await visitsFor(l,p);if(!visits.length){await send(chat,`📌 ${p.code||""} · ${cleanProjectName(p)}\nEste proyecto todavía no tiene visitas registradas.`);return}let num=requestedVisitNumber(text);if(!num&&wantsLastVisit(text))num=Number(visits[visits.length-1].visit_number);if(num){await prepareVisitReport(chat,l,p,num,fmt);return}const {data:d,error}=await db.from("assistant_drafts").insert({workspace_id:l.workspace_id,project_id:p.id,draft_type:"generate_report",title:`Informe · ${p.code||"Proyecto"}`,source_text:text,summary:"Solicitud de informe de visitas desde Telegram",parsed_data:{report_type:"visitas",evidence_ids:[ZERO_ID],request_text:text,context_text:"",visit_selection:null},status:"draft",created_by:l.user_id}).select("id").single();if(error)throw error;const rows=visits.map((v:any)=>[{text:`📍 N.º ${v.visit_number} · ${dateHN(v.visit_date)}`,callback_data:`rv:${d.id}:${v.visit_number}`}]);rows.push([{text:"📚 Todas las visitas",callback_data:`rv:${d.id}:all`}]);rows.push([{text:"❌ Cancelar",callback_data:`cancel:${d.id}`}]);await send(chat,`📄 INFORMES DE VISITA\n📌 ${p.code||""} · ${cleanProjectName(p)}\n\n¿Qué visita deseas generar?`,{inline_keyboard:rows});return}
const {data:d,error}=await db.from("assistant_drafts").insert({workspace_id:l.workspace_id,project_id:p.id,draft_type:"generate_report",title:`Informe · ${p.code||"Proyecto"}`,source_text:text,summary:"Solicitud de informe desde Telegram",parsed_data:{report_type:rt,evidence_ids:[ZERO_ID],request_text:text,context_text:"",visit_selection:null},status:"draft",created_by:l.user_id}).select("id").single();if(error)throw error;await send(chat,`📄 Informe preparado\n📌 ${p.code||""} · ${cleanProjectName(p)}\n\n¿En qué formato?`,formatKeyboard(d.id))}
async function sanitizeDraftVisitImages(l:any,draftId:string){const {data:d}=await db.from("assistant_drafts").select("project_id,parsed_data").eq("id",draftId).eq("workspace_id",l.workspace_id).maybeSingle();if(!d)return null;const pd=d.parsed_data||{};if(pd.report_type!=="visitas")return null;const sel=String(pd.visit_selection??"");let rows:any[]=[];if(sel.toLowerCase()==="all"){const {data:v}=await db.from("visits").select("id,visit_number").eq("workspace_id",l.workspace_id).eq("project_id",d.project_id).is("voided_at",null).order("visit_number");rows=v||[];await db.from("assistant_drafts").update({parsed_data:{...pd,evidence_ids:[ZERO_ID]},updated_at:new Date().toISOString()}).eq("id",draftId)}else{const n=Number(sel);if(!Number.isFinite(n)||n<=0)return null;const {data:v}=await db.from("visits").select("id,visit_number").eq("workspace_id",l.workspace_id).eq("project_id",d.project_id).eq("visit_number",n).is("voided_at",null).maybeSingle();if(v){rows=[v];const p=await getProject(l,d.project_id);if(p){const ids=await evidenceIdsForVisit(l,p,v.id);await db.from("assistant_drafts").update({parsed_data:{...pd,evidence_ids:ids},updated_at:new Date().toISOString()}).eq("id",draftId)}}}let valid=0,rejected=0,registered=0;for(const v of rows.slice(0,30)){const x=await sanitizeVisitImages(v.id);valid+=Number(x.valid||0);rejected+=Number(x.rejected||0);registered+=Number(x.registered||0)}return{visits:rows.length,valid,rejected,registered}}

async function showActiveVisit(chat:any,l:any){const s=await activeSession(l);if(!s){await send(chat,"📸 No hay una visita activa o pendiente de revisión.");return}const p=await getProject(l,s.project_id),count=await visitCount(s.id);await send(chat,`📸 VISITA ACTUAL\n📌 ${p?.code||""} · ${p?cleanProjectName(p):"Proyecto"}\nEstado: ${s.status==="active"?"Activa":"En revisión"}\nEvidencias: ${count}\nInicio: ${dateHN(s.created_at)}`)}
async function showProjectInfo(chat:any,l:any,text:string){const p=await resolveProject(l,text,true);if(!p){await send(chat,"No pude identificar el proyecto.");return}const s=await snapshot(l,p.id),co=s?.contract||{},pr=s?.project||p,n=norm(text),lines:string[]=[`📌 ${pr.code||p.code||""} · ${cleanProjectName(pr)}`];const specific=/monto contratado|contratista|plazo|finalizacion|firma|anticipo|pagos|estimaciones|garantias|garantia/.test(n);if(!specific||/estado/.test(n))lines.push(`Estado: ${pr.status||p.status||"No registrado"}.`);if(!specific||/monto contratado/.test(n))lines.push(`Monto contratado: ${co.original_amount??pr.budget_estimate??p.budget_estimate!=null?money(co.original_amount??pr.budget_estimate??p.budget_estimate):"No registrado"}.`);if(!specific||/contratista/.test(n))lines.push(`Contratista: ${co.contractor||"No registrado"}.`);if(/firma/.test(n))lines.push(`Fecha de firma: ${dateHN(co.signature_date)}.`);if(!specific||/plazo|finalizacion/.test(n))lines.push(`Plazo: ${co.execution_days??pr.execution_days??"No registrado"} días${co.end_date||pr.end_date?` · finalización ${dateHN(co.end_date||pr.end_date)}`:""}.`);if(/anticipo/.test(n))lines.push(`Anticipo: ${co.advance_paid!=null?money(co.advance_paid):"No registrado"}${co.advance_payment_date?` · ${dateHN(co.advance_payment_date)}`:""}.`);if(/pagos/.test(n))lines.push(`Pagos registrados: ${money(s?.payments_total||0)} (${s?.payments_count||0}).`);if(/estimaciones/.test(n))lines.push(`Estimaciones: ${s?.estimate_count||0} · neto ${money(s?.estimates_net||0)}.`);if(/garantia/.test(n))lines.push(`Garantías registradas: ${s?.guarantee_count||0}.`);if(!specific)lines.push(`Visitas registradas: ${s?.visit_count||0}${s?.latest_visit?` · última N.º ${s.latest_visit.visit_number} del ${dateHN(s.latest_visit.visit_date)}`:""}.`);await send(chat,lines.join("\n"))}
async function selectProject(chat:any,l:any,text:string){const s=await activeSession(l);if(s?.status==="active"){const ap=await getProject(l,s.project_id);await send(chat,`Hay una visita activa en ${ap?.code||"otro proyecto"} · ${ap?cleanProjectName(ap):""}.\nPara proteger la evidencia, finaliza o cancela esa visita antes de cambiar de proyecto.`);return}const p=await resolveProject(l,text,false);if(!p){const q=queryTerms(text),rows=q?await searchProjects(l,q,5):[];await send(chat,rows.length?`No pude identificar un único proyecto:\n${rows.map((x:any)=>`• ${x.code||""} · ${x.name||""}`).join("\n")}`:"No pude identificar el proyecto.");return}await db.from("telegram_links").update({current_project_id:p.id,updated_at:new Date().toISOString()}).eq("id",l.id);l.current_project_id=p.id;await send(chat,`📌 Proyecto activo:\n${p.code||""} · ${cleanProjectName(p)}`)}
async function gem(input:string){if(!G)throw new Error("Gemini no está configurado");const r=await fetch("https://generativelanguage.googleapis.com/v1beta/interactions",{method:"POST",headers:{"content-type":"application/json","x-goog-api-key":G,"Api-Revision":"2026-05-20"},body:JSON.stringify({model:FAST,input})}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(clean(d?.error?.message||`Gemini ${r.status}`,500));const out:string[]=[];const add=(x:any)=>{if(typeof x==="string"&&x.trim())out.push(x.trim())};add(d?.output_text);for(const x of d?.output||[]){add(x?.text);for(const y of x?.content||[])add(y?.text)}for(const s of d?.steps||[])for(const q of[s?.model_output,s?.output,s]){add(q?.text);add(q?.output_text);for(const x of q?.content||[])add(x?.text)}return[...new Set(out)].join("\n")}
async function answerAction(chat:any,l:any,text:string){const p=await resolveProject(l,text,true);let context="";if(p){try{context=JSON.stringify(await snapshot(l,p.id)).slice(0,14000)}catch{context=JSON.stringify(p)}}const reply=await gem(`Eres el Ingeniero Móvil de Control Contractual. Responde en español de forma breve, práctica y profesional. La petición del usuario parece una orden o consulta, NO una nota de campo. Usa únicamente los datos del expediente proporcionado; no inventes. Si pide una operación que no puedes ejecutar con los datos disponibles, indica exactamente qué falta sin mostrar errores técnicos.\nExpediente: ${context||"No identificado"}\nPetición: ${text}`);await send(chat,reply||"No pude completar la orden con la información disponible.")}
function rewriteText(u:any,newText:string){const x=structuredClone(u);if(x?.message)x.message.text=newText;else if(x?.edited_message)x.edited_message.text=newText;return x}
async function proxy(u:any){const r=await fetch(GATEWAY,{method:"POST",headers:{"content-type":"application/json","x-telegram-bot-api-secret-token":await sha(T)},body:JSON.stringify(u)}),body=await r.text();return new Response(body,{status:r.status,headers:{"content-type":"application/json","cache-control":"no-store"}})}

Deno.serve(async req=>{try{
 if(req.method==="GET")return json({ok:true,service:"telegram-router",version:"3.2-workspace-isolated"});
 if(req.method!=="POST")return json({error:"method"},405);
 if((req.headers.get("x-telegram-bot-api-secret-token")??"")!==await sha(T))return json({error:"unauthorized"},401);
 const u=await req.json(),m=u?.message??u?.edited_message??u?.callback_query?.message,f=u?.message?.from??u?.edited_message?.from??u?.callback_query?.from,chat=m?.chat?.id,tid=f?.id;
 if(!chat||!tid)return json({ok:true});const l=await linkFor(tid);if(!l)return proxy(u);

 if(u.callback_query){const d=clean(u.callback_query.data,100);try{await tg("answerCallbackQuery",{callback_query_id:u.callback_query.id,text:"Procesando..."})}catch{}
   if(d.startsWith("vqp:")){const [,pid,n0]=d.split(":"),p=await getProject(l,pid),n=Number(n0);if(p&&n>0)await showVisitForProject(chat,l,p,n);return json({ok:true,visit_query:true})}
   if(d.startsWith("vqpl:")){const pid=d.slice(5),p=await getProject(l,pid);if(p)await showVisitListForProject(chat,l,p);return json({ok:true,visit_list:true})}
   if(d.startsWith("vrp:")){const [,pid,n0,fmt]=d.split(":"),p=await getProject(l,pid),n=Number(n0);if(!p||!n||!["pdf","docx","both"].includes(fmt))return json({ok:false,error:"invalid_visit_export"},400);await prepareVisitReport(chat,l,p,n,fmt);return json({ok:true,visit_export:true})}
   if(d.startsWith("vrrp:")){const [,pid,n0]=d.split(":"),p=await getProject(l,pid),n=Number(n0);if(!p||!n)return json({ok:false},400);const v=await getVisit(l,p,n);if(!v){await send(chat,`No encontré la visita N.º ${n}.`);return json({ok:true})}try{await sanitizeVisitImages(v.id);const r=await reloadCall({action:"start",link_id:l.id,visit_id:v.id,chat_id:chat});if(!r.started&&r.reason==="no_invalid_photos")await send(chat,"✅ Todas las fotografías de esta visita ya están válidas; no hace falta recargarlas.");return json({ok:true,photo_reload:true})}catch(err){await send(chat,`No pude iniciar la recarga: ${clean(err instanceof Error?err.message:err,500)}`);return json({ok:false})}}
   if(d.startsWith("vq:")){if(d==="vq:list")await showVisitList(chat,l);else{const n=Number(d.slice(3));if(n>0)await showVisit(chat,l,n)}return json({ok:true,legacy_visit_query:true})}
   if(d.startsWith("vrr:")){const n=Number(d.slice(4)),p=await currentProject(l);if(p&&n>0){const v=await getVisit(l,p,n);if(v){await sanitizeVisitImages(v.id);await reloadCall({action:"start",link_id:l.id,visit_id:v.id,chat_id:chat})}}return json({ok:true,legacy_reload:true})}
   if(d.startsWith("vrf:")){const [,n0,fmt]=d.split(":"),n=Number(n0),p=await currentProject(l);if(p&&n>0&&["pdf","docx","both"].includes(fmt)){await prepareVisitReport(chat,l,p,n,fmt);return json({ok:true,legacy_visit_export:true})}return json({ok:false},400)}
   if(d.startsWith("rv:")){const [,draftId,sel]=d.split(":"),{data:dr}=await db.from("assistant_drafts").select("project_id,parsed_data").eq("id",draftId).eq("workspace_id",l.workspace_id).maybeSingle();if(!dr)return json({ok:false,error:"draft_not_found"},404);const pd=dr.parsed_data||{};let ids=[ZERO_ID];if(sel!=="all"){const p=await getProject(l,dr.project_id),v=p?await getVisit(l,p,Number(sel)):null;if(v&&p)ids=await evidenceIdsForVisit(l,p,v.id)}await db.from("assistant_drafts").update({parsed_data:{...pd,visit_selection:sel,evidence_ids:ids},updated_at:new Date().toISOString()}).eq("id",draftId);await send(chat,`📄 ${sel==="all"?"Todas las visitas":"Visita N.º "+sel} seleccionada(s).\n¿En qué formato?`,formatKeyboard(draftId));return json({ok:true,visit_selected:true})}
   if(d.startsWith("rf:")){const [,draftId,fmt]=d.split(":");try{const check=await sanitizeDraftVisitImages(l,draftId);if(check){if(Number(check.rejected||0)>0)await send(chat,`⚠️ Antes de generar revisé las fotografías: ${check.valid} válida(s) y ${check.rejected} dañada(s). Las dañadas serán omitidas.`);const r=await exportVisitDraft(l,draftId,fmt,chat);return json({ok:true,visit_export:true,...r})}}catch(err){await send(chat,`No generaré el informe hasta validar correctamente las fotografías: ${clean(err instanceof Error?err.message:err,420)}`);return json({ok:false,image_validation:false})}return proxy(u)}
   if(d.startsWith("cancel:")){await db.from("assistant_drafts").update({status:"rejected",updated_at:new Date().toISOString()}).eq("id",d.slice(7)).eq("workspace_id",l.workspace_id);await send(chat,"❌ Operación cancelada.");return json({ok:true,cancelled:true})}
   return proxy(u);
 }

 if(m?.photo?.length){try{const rr=await reloadCall({action:"photo",link_id:l.id,update:u});if(rr?.handled)return json({ok:true,historical_photo_reload:true})}catch(err){await send(chat,`No pude guardar la fotografía de recarga: ${clean(err instanceof Error?err.message:err,500)}. Vuelve a enviarla.`);return json({ok:false})}}

 const text=clean(m?.text??m?.caption??"",1000),nt=norm(text);
 if(text&&(text.toLowerCase().startsWith("/cancelarrecarga")||/\bcancelar recarga(?: fotografica)?\b/.test(nt))){try{const r=await reloadCall({action:"cancel",link_id:l.id,chat_id:chat});if(!r.cancelled)await send(chat,"No hay una recarga fotográfica activa.");return json({ok:true})}catch(err){await send(chat,`No pude cancelar la recarga: ${clean(err instanceof Error?err.message:err,400)}`);return json({ok:false})}}

 if(text){
   if(wantsReport(text)){await startNaturalReport(chat,l,text);return json({ok:true,natural_report:true})}
   if(wantsActiveVisit(text)){await showActiveVisit(chat,l);return json({ok:true,active_visit:true})}
   if(wantsVisitList(text)){await showVisitList(chat,l,text);return json({ok:true,visit_list:true})}
   const vn=requestedVisitNumber(text);if(vn){await showVisit(chat,l,vn,text);return json({ok:true,visit_detail:true,visit_number:vn})}
   if(wantsSelectProject(text)){await selectProject(chat,l,text);return json({ok:true,select_project:true})}
   if(wantsProjectInfo(text)){await showProjectInfo(chat,l,text);return json({ok:true,project_info:true})}
   if(isFinishVisit(text))return proxy(rewriteText(u,"/finalizar"));
   if(isCancelVisit(text))return proxy(rewriteText(u,"/cancelarvisita"));
   if(isStartVisit(text)){const q=queryTerms(text);return proxy(rewriteText(u,`/visita ${q}`.trim()))}
   const s=await activeSession(l);
   if(s?.status==="active"&&actionLike(text)){try{await answerAction(chat,l,text);return json({ok:true,action_answer:true})}catch(err){await send(chat,`No pude completar la orden: ${clean(err instanceof Error?err.message:err,400)}`);return json({ok:false})}}
 }
 return proxy(u);
}catch(err){console.error("router",err);return json({ok:false,error:clean(err instanceof Error?err.message:err,500)},500)}});