/* ===== CONTROL CONTRACTUAL · INGENIERÍA CIVIL + UX OPERATIVA V1 ===== */
(()=>{
'use strict';
if(window.__CC_ENGINEERING_UX_V1__)return;window.__CC_ENGINEERING_UX_V1__=true;
const H=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const A=v=>Array.isArray(v)?v:[],N=v=>Number(v)||0,R=v=>Math.round(N(v)*100)/100;
const M=v=>`L ${R(v).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const P=v=>`${R(v).toFixed(2)}%`;
const say=m=>{try{toast(m)}catch{console.log(m)}};
let projectCache={at:0,map:new Map()},qualityCache={at:0,data:null};
function styles(){if(document.getElementById('cc-engineering-ux-style'))return;const s=document.createElement('style');s.id='cc-engineering-ux-style';s.textContent=`
#backupBtn,#newProjectBtn,[data-purge]{display:none!important}.cc-eng-progress{display:flex;gap:6px;flex-wrap:wrap;margin:8px 0 0}.cc-eng-chip{border:1px solid #25384e;background:#0a1420;border-radius:999px;padding:5px 7px;font-size:8px;color:#9db0c3}.cc-eng-chip b{color:#eef5fc}.cc-eng-chip.warn{border-color:#695b1f;background:#28230b;color:#fde68a}.cc-eng-chip.danger{border-color:#6d2b31;background:#291014;color:#fecaca}.cc-eng-impact{grid-column:1/-1;border:1px solid #24415f;border-radius:13px;background:linear-gradient(145deg,#0b1826,#08111a);padding:11px}.cc-eng-impact h4{margin:0 0 8px;font-size:11px}.cc-eng-impact-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:7px}.cc-eng-impact-grid div{padding:8px;border:1px solid #1d2d40;border-radius:10px;background:#081019}.cc-eng-impact-grid small{display:block;color:#71869b;font-size:7px}.cc-eng-impact-grid b{display:block;font-size:11px;margin-top:3px}.cc-eng-impact.ok{border-color:#28543c}.cc-eng-impact.bad{border-color:#6e2e33;background:#241014}.cc-eng-impact.bad .cc-eng-balance{color:#fca5a5}.cc-data-quality{border:1px solid #705b1c;background:linear-gradient(145deg,#241f0b,#15150d);border-radius:13px;padding:11px}.cc-data-quality summary{cursor:pointer;font-weight:850;color:#fde68a;font-size:10px}.cc-data-quality-list{display:grid;gap:6px;margin-top:9px}.cc-data-quality-row{padding:8px;border:1px solid rgba(234,179,8,.16);border-radius:9px;background:rgba(0,0,0,.12);font-size:8px}.cc-data-quality-row b{display:block;color:#f8e9a2;font-size:9px}.cc-data-quality-row small{display:block;color:#b6a768;margin-top:3px}.cc-human-note{grid-column:1/-1;border:1px solid #23415f;background:#0b1a29;color:#b9d5ef;border-radius:10px;padding:9px 10px;font-size:9px}.cc-void-note{font-size:8px;color:#8297ad}.project-card-premium .project-progress .progress-label span{font-weight:700}
@media(max-width:620px){.cc-eng-impact-grid{grid-template-columns:1fr 1fr}}
@media(max-width:420px){.cc-eng-impact-grid{grid-template-columns:1fr}}
`;document.head.appendChild(s)}
function currentContract(c){if(!c)return 0;const delta=A(db?.changes).filter(x=>x.contractId===c.id&&x.status==='Aprobado'&&!x.voidedAt&&!x.voided_at).reduce((s,x)=>s+N(x.amountDelta),0);return R(N(c.originalAmount)+delta)}
async function serverProjects(force=false){if(!force&&Date.now()-projectCache.at<45000&&projectCache.map.size)return projectCache.map;let w;try{w=cloudWorkspaceId}catch{return projectCache.map}if(!w||!navigator.onLine||typeof sbFetch!=='function')return projectCache.map;try{const r=await sbFetch(`/rest/v1/project_financial_summary?select=project_id,current_amount,estimated_total,paid_total,contractual_balance,financial_progress_pct,physical_progress_pct,time_progress_pct,highest_alert_severity,alert_count&workspace_id=eq.${encodeURIComponent(w)}`);projectCache={at:Date.now(),map:new Map(A(r.data).map(x=>[x.project_id,x]))};return projectCache.map}catch(e){console.warn('Resumen de ingeniería:',e);return projectCache.map}}
function decorateCard(card,row){if(!card||!row)return;const label=card.querySelector('.project-progress .progress-label span');if(label)label.textContent='Avance financiero (estimado acumulado)';const value=card.querySelector('.project-progress .progress-label b');if(value)value.textContent=P(row.financial_progress_pct);const fill=card.querySelector('.project-progress .progress-fill');if(fill)fill.style.width=Math.min(100,Math.max(0,N(row.financial_progress_pct)))+'%';let box=card.querySelector('.cc-eng-progress');if(!box){box=document.createElement('div');box.className='cc-eng-progress';(card.querySelector('.project-progress')||card.querySelector('.project-meta')||card).insertAdjacentElement('afterend',box)}const physical=row.physical_progress_pct==null?'Sin registrar':P(row.physical_progress_pct),time=row.time_progress_pct==null?'Sin plazo':P(row.time_progress_pct),gap=row.physical_progress_pct==null||row.time_progress_pct==null?null:N(row.time_progress_pct)-N(row.physical_progress_pct),bad=N(row.financial_progress_pct)>100.005;box.innerHTML=`<span class="cc-eng-chip"><b>Físico:</b> ${physical}</span><span class="cc-eng-chip ${bad?'danger':''}"><b>Financiero:</b> ${P(row.financial_progress_pct)}</span><span class="cc-eng-chip"><b>Tiempo:</b> ${time}</span>${gap!=null&&gap>=20?`<span class="cc-eng-chip warn"><b>Atención:</b> avance físico rezagado ${P(gap)}</span>`:''}${bad?'<span class="cc-eng-chip danger"><b>INCONSISTENCIA:</b> avance financiero > 100%</span>':''}`}
async function decorateCards(){const map=await serverProjects();document.querySelectorAll('.project-card-premium,.project-v3').forEach(card=>{const id=card.querySelector('[data-open]')?.dataset.open||card.querySelector('[data-cp-budget-open]')?.dataset.cpBudgetOpen;if(id&&map.has(id))decorateCard(card,map.get(id))})}
function estimateImpact(){const form=document.getElementById('estForm'),gross=document.getElementById('eGross');if(!form||!gross)return;const physical=document.getElementById('ePhysical'),field=physical?.closest('.field');if(field){const label=field.querySelector('span');if(label)label.textContent='Avance financiero automático %';const small=field.querySelector('small');if(small)small.textContent='Estimado acumulado ÷ monto contractual vigente. El avance físico se registra en Supervisión / Visitas de campo.'}let panel=form.querySelector('.cc-eng-impact');if(!panel){panel=document.createElement('section');panel.className='cc-eng-impact';const actions=form.querySelector('.modal-actions');actions?.before(panel)}let project;try{project=A(db.projects).find(x=>x.id===view.projectId)}catch{return}const c=A(db.contracts).find(x=>x.projectId===project?.id);if(!c)return;const title=form.closest('.modal')?.querySelector('.modal-head h2')?.textContent||'',num=Number(title.match(/N\.º\s*(\d+)/i)?.[1]||0),editing=A(db.estimates).find(x=>x.contractId===c.id&&Number(x.number)===num),priorC=A(db.estimates).filter(x=>x.contractId===c.id&&x.id!==editing?.id&&!x.voidedAt&&!x.voided_at&&x.status!=='Anulada').reduce((s,x)=>s+Math.round(N(x.gross)*100),0),currentC=Math.round(currentContract(c)*100);const update=()=>{const thisC=Math.round(N(gross.value)*100),afterC=priorC+thisC,balanceC=currentC-afterC,progress=currentC?afterC/currentC*100:0,bad=balanceC<0;panel.className='cc-eng-impact '+(bad?'bad':'ok');panel.innerHTML=`<h4>Impacto contractual antes de guardar</h4><div class="cc-eng-impact-grid"><div><small>Monto contractual vigente</small><b>${M(currentC/100)}</b></div><div><small>Estimado acumulado previo</small><b>${M(priorC/100)}</b></div><div><small>Esta estimación</small><b>${M(thisC/100)}</b></div><div><small>Saldo posterior</small><b class="cc-eng-balance">${M(balanceC/100)}</b></div></div><div class="cc-human-note">${bad?`No se puede guardar: excedería el contrato en ${M(Math.abs(balanceC)/100)}. Máximo permitido para esta estimación: ${M(Math.max(0,currentC-priorC)/100)}.`:`Después de guardar, el avance financiero sería ${P(progress)}. El avance físico se mantiene independiente y proviene de supervisión de campo.`}</div>`;if(physical)physical.value=P(progress)};gross.addEventListener('input',update);update()}
function renameDangerous(){document.querySelectorAll('[data-trash]').forEach(b=>{b.textContent='Archivar';b.title='Archiva el expediente sin eliminar su historial.'});document.querySelectorAll('[data-del-est],[data-del-movement],[data-del-g],[data-budget-delete-move],[data-del-visit]').forEach(b=>{b.textContent='Anular';b.title='Anula el registro y conserva la trazabilidad.'});document.querySelectorAll('[data-purge]').forEach(b=>{b.hidden=true;b.setAttribute('aria-hidden','true')})}
function archiveLocal(key,archiveKey,id,status,reason){const list=A(db[key]),i=list.findIndex(x=>x.id===id);if(i<0)return null;db[archiveKey]=A(db[archiveKey]);const row=list[i];row.voidedAt=typeof iso==='function'?iso():new Date().toISOString();row.voidedBy=session?.userId||null;row.voidReason=reason;if(status)row.status=status;list.splice(i,1);db[archiveKey].unshift(row);return row}
async function rpc(name,body,notFound='NO_ENCONTRAD'){try{await sbFetch('/rest/v1/rpc/'+name,{method:'POST',body});return true}catch(e){if(String(e?.message||'').includes(notFound))return false;throw e}}
async function voidMovement(id){const x=A(db.payments).find(z=>z.id===id);if(!x)return;const reason=prompt(`Motivo de anulación del movimiento financiero${x.movementType?' '+x.movementType:''}:`);if(!reason?.trim())return;try{await rpc('void_payment',{p_payment_id:id,p_reason:reason.trim()},'PAGO_NO_ENCONTRADO');archiveLocal('payments','voidedPayments',id,'Anulado',reason.trim());audit?.('ANULAR','Movimiento financiero',id,{reason:reason.trim(),projectId:x.projectId,contractId:x.contractId});saveDB();renderProject();say('Movimiento anulado. El historial fue conservado.')}catch(e){say(e.message||'No se pudo anular.') }}
async function voidGuarantee(id){const g=A(db.guarantees).find(x=>x.id===id);if(!g)return;const reason=prompt(`Motivo de anulación de la garantía ${g.type||''}:`);if(!reason?.trim())return;try{await rpc('void_guarantee',{p_guarantee_id:id,p_reason:reason.trim()},'GARANTIA_NO_ENCONTRADA');archiveLocal('guarantees','voidedGuarantees',id,'Anulada',reason.trim());audit?.('ANULAR','Garantía',id,{reason:reason.trim(),type:g.type,projectId:g.projectId});saveDB();renderProject();say('Garantía anulada. El historial fue conservado.')}catch(e){say(e.message||'No se pudo anular.') }}
async function voidVisit(id){const v=A(db.visits).find(x=>x.id===id);if(!v)return;const reason=prompt(`Motivo de anulación de la visita N.º ${v.number}:`);if(!reason?.trim())return;try{await rpc('void_visit',{p_visit_id:id,p_reason:reason.trim()},'VISITA_NO_ENCONTRADA');archiveLocal('visits','voidedVisits',id,'Anulada',reason.trim());audit?.('ANULAR','Visita',id,{reason:reason.trim(),number:v.number,projectId:v.projectId});saveDB();renderProject();say('Visita anulada. Sus datos permanecen en auditoría.')}catch(e){say(e.message||'No se pudo anular.') }}
async function voidBudgetMovement(id){let p;try{p=A(db.projects).find(x=>x.id===view.projectId)}catch{}const b=p?.budgetControl,m=A(b?.movements).find(x=>x.id===id);if(!p||!m)return;const reason=prompt(`Motivo de anulación del movimiento ${m.type} por ${M(m.amount)}:`);if(!reason?.trim())return;try{await rpc('void_budget_movement',{p_movement_id:id,p_reason:reason.trim()},'MOVIMIENTO_NO_ENCONTRADO');b.voidedMovements=A(b.voidedMovements);b.movements=b.movements.filter(x=>x.id!==id);m.voidedAt=typeof iso==='function'?iso():new Date().toISOString();m.voidReason=reason.trim();b.voidedMovements.unshift(m);audit?.('ANULAR','Movimiento presupuestario',id,{reason:reason.trim(),projectId:p.id,type:m.type,amount:m.amount});saveDB();renderProject();say('Movimiento presupuestario anulado.')}catch(e){say(e.message||'No se pudo anular.') }}
async function archiveProject(id){const p=A(db.projects).find(x=>x.id===id);if(!p)return;const reason=prompt(`Motivo para archivar el proyecto ${p.code||''}:`);if(!reason?.trim())return;try{await sbFetch('/rest/v1/rpc/archive_project',{method:'POST',body:{p_project_id:id,p_reason:reason.trim()}});p.deletedAt=typeof iso==='function'?iso():new Date().toISOString();p.deletedBy=session?.userId||null;p.deletedReason=reason.trim();audit?.('ARCHIVAR','Proyecto',id,{reason:reason.trim(),code:p.code});saveDB();renderApp();say('Proyecto archivado. No se eliminó información.')}catch(e){say(e.message||'No se pudo archivar.') }}
async function restoreProject(id){const p=A(db.projects).find(x=>x.id===id);if(!p)return;try{await sbFetch('/rest/v1/rpc/restore_project',{method:'POST',body:{p_project_id:id}});p.deletedAt=null;p.deletedBy=null;p.deletedReason='';audit?.('RESTAURAR','Proyecto',id,{code:p.code});saveDB();renderApp();say('Proyecto restaurado.')}catch(e){say(e.message||'No se pudo restaurar.') }}
async function quality(){if(Date.now()-qualityCache.at<45000&&qualityCache.data)return qualityCache.data;let w;try{w=cloudWorkspaceId}catch{return null}if(!w||!navigator.onLine)return null;try{const r=await sbFetch('/rest/v1/rpc/get_control_center',{method:'POST',body:{p_workspace_id:w}});qualityCache={at:Date.now(),data:r.data?.data_quality||null};return qualityCache.data}catch{return null}}
async function decorateQuality(){const q=await quality();if(!q||!N(q.pending))return;const page=document.querySelector('.ccx-page');if(!page)return;const home=page.querySelector('.ccx-access'),audit=page.querySelector('.ccx-integrity');if(!home&&!audit)return;let box=document.getElementById('ccDataQuality');if(!box){box=document.createElement('details');box.id='ccDataQuality';box.className='cc-data-quality';(audit||home).insertAdjacentElement('afterend',box)}box.innerHTML=`<summary>Saneamiento documental pendiente · ${N(q.pending)} registro(s)</summary><div class="cc-data-quality-list">${A(q.items).slice(0,18).map(x=>`<div class="cc-data-quality-row"><b>${H(x.entity_type)} · ${H(x.issue_code)}</b>${H(x.description||'Dato histórico incompleto')}<small>Respaldo requerido: ${H(x.required_evidence||'verificar contra expediente original')}</small></div>`).join('')}</div>`}
function decorateForms(){estimateImpact();const form=document.getElementById('gForm');if(form&&!form.querySelector('.cc-human-note')){const n=document.createElement('div');n.className='cc-human-note';n.textContent='Número, emisor, vigencia y referencia documental son obligatorios para una garantía vigente.';form.prepend(n)}const b=document.getElementById('budgetMoveForm');if(b&&!b.querySelector('.cc-human-note')){const n=document.createElement('div');n.className='cc-human-note';n.textContent='Todo movimiento presupuestario debe tener una referencia documental. El saldo disponible se calcula automáticamente; no se captura manualmente.';b.prepend(n)}}
async function decorate(){styles();renameDangerous();decorateForms();await decorateCards();await decorateQuality()}
document.addEventListener('click',e=>{const purge=e.target.closest?.('[data-purge]');if(purge){e.preventDefault();e.stopImmediatePropagation();say('La eliminación definitiva está deshabilitada. Utiliza Archivar para conservar la trazabilidad.');return}const t=e.target.closest?.('[data-trash]');if(t){e.preventDefault();e.stopImmediatePropagation();archiveProject(t.dataset.trash);return}const rs=e.target.closest?.('[data-restore]');if(rs){e.preventDefault();e.stopImmediatePropagation();restoreProject(rs.dataset.restore);return}const mv=e.target.closest?.('[data-del-movement]');if(mv){e.preventDefault();e.stopImmediatePropagation();voidMovement(mv.dataset.delMovement);return}const g=e.target.closest?.('[data-del-g]');if(g){e.preventDefault();e.stopImmediatePropagation();voidGuarantee(g.dataset.delG);return}const bm=e.target.closest?.('[data-budget-delete-move]');if(bm){e.preventDefault();e.stopImmediatePropagation();voidBudgetMovement(bm.dataset.budgetDeleteMove);return}const v=e.target.closest?.('[data-del-visit]');if(v){e.preventDefault();e.stopImmediatePropagation();voidVisit(v.dataset.delVisit);return}},true);
try{if(typeof renderApp==='function'&&!renderApp.__ccEngineeringUX){const base=renderApp;renderApp=function(){const r=base.apply(this,arguments);setTimeout(()=>decorate().catch(console.error),0);return r};renderApp.__ccEngineeringUX=true}}catch(e){console.warn(e)}
try{if(typeof renderProject==='function'&&!renderProject.__ccEngineeringUX){const base=renderProject;renderProject=function(){const r=base.apply(this,arguments);setTimeout(()=>decorate().catch(console.error),0);return r};renderProject.__ccEngineeringUX=true}}catch(e){console.warn(e)}
document.addEventListener('input',e=>{if(e.target?.id==='eGross')setTimeout(estimateImpact,0)},true);
styles();setTimeout(()=>decorate().catch(()=>{}),0);setTimeout(()=>decorate().catch(()=>{}),500);
})();
