/* ===== ZORDON · PORTADA CONSTRUCCIÓN E INGENIERÍA V2 ===== */
(()=>{
'use strict';
if(typeof window==='undefined'||typeof document==='undefined')return;
if(window.__CC_INDUSTRIAL_HOME_V2__)return;
window.__CC_INDUSTRIAL_HOME_V2__=true;
window.__CC_INDUSTRIAL_HOME_V1__=true;
const A='assets/industrial/';
const IMG={
 hero:A+'generated-construction-hero.webp',
 projects:A+'generated-construction-hero.webp',
 engineering:A+'generated-engineering-bridge.webp',
 supervision:A+'generated-supervision-site.webp',
 audit:A+'generated-supervision-site.webp',
 budget:A+'generated-engineering-bridge.webp',
 contracts:A+'generated-construction-hero.webp'
};
const norm=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\s+/g,' ').trim();
function css(){
 if(document.getElementById('cc-industrial-home-style'))return;
 const s=document.createElement('style');s.id='cc-industrial-home-style';s.textContent=`
 .cc-industrial-home{position:relative;overflow:hidden;border:1px solid #2b435a;border-radius:18px;background:#07111c;color:#f4f8fc;box-shadow:0 18px 44px rgba(0,0,0,.24);margin:0 0 12px}
 .cc-industrial-hero{min-height:280px;display:grid;grid-template-columns:minmax(0,1.05fr) minmax(360px,.95fr);background:radial-gradient(circle at 82% 12%,rgba(26,107,175,.28),transparent 34%),linear-gradient(116deg,#07111c 0%,#0a1a29 52%,#102438 100%)}
 .cc-industrial-copy{position:relative;z-index:2;padding:36px;display:flex;flex-direction:column;justify-content:center}.cc-industrial-kicker{font-size:9px;font-weight:900;letter-spacing:.22em;color:#59b9ff;text-transform:uppercase}.cc-industrial-home .cc-industrial-title{margin:9px 0 8px!important;font-size:clamp(30px,3.3vw,54px)!important;line-height:.9!important;letter-spacing:-.045em!important;text-transform:uppercase}.cc-industrial-title span,.cc-industrial-title em{display:block}.cc-industrial-title em{font-style:normal;color:#7ec9ff}.cc-industrial-copy p{max-width:650px;margin:0;color:#a9bbcc;font-size:11px;line-height:1.55}.cc-industrial-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:17px}.cc-industrial-actions button{min-height:34px;padding:7px 11px;border-radius:8px;border:1px solid #31516e;background:#10243a;color:#eaf5ff;font-size:9px;font-weight:850;cursor:pointer}.cc-industrial-actions button.primary{background:#1c73d8;border-color:#2d8cf3}
 .cc-industrial-art{position:relative;min-height:280px;background-image:linear-gradient(90deg,#07111c 0%,rgba(7,17,28,.72) 14%,rgba(7,17,28,.06) 60%),var(--cc-hero-img);background-size:cover;background-position:center;box-shadow:inset 35px 0 55px rgba(7,17,28,.72)}.cc-industrial-art:after{content:'';position:absolute;inset:auto 0 0;height:42%;background:linear-gradient(transparent,rgba(7,17,28,.94))}.cc-industrial-badge{position:absolute;right:20px;bottom:17px;z-index:2;border:1px solid rgba(255,255,255,.18);background:rgba(5,15,25,.72);backdrop-filter:blur(8px);border-radius:10px;padding:8px 10px}.cc-industrial-badge b{display:block;font-size:10px}.cc-industrial-badge span{display:block;margin-top:2px;color:#9fb3c5;font-size:8px}
 .cc-industrial-services{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:1px;background:#24394c;border-top:1px solid #29435b}.cc-industrial-service{position:relative;min-height:112px;border:0;background:#0b1825;color:#fff;overflow:hidden;cursor:pointer;text-align:left;padding:0}.cc-industrial-service:before{content:'';position:absolute;inset:0;background-image:linear-gradient(180deg,rgba(3,11,18,.03),rgba(3,11,18,.9)),var(--cc-service-img);background-size:cover;background-position:center;transition:transform .22s ease,filter .22s ease}.cc-industrial-service:hover:before{transform:scale(1.045);filter:saturate(1.08)}.cc-industrial-service div{position:absolute;left:10px;right:10px;bottom:9px;z-index:2}.cc-industrial-service small{display:block;color:#8dccff;font-size:7px;font-weight:900;letter-spacing:.09em;text-transform:uppercase}.cc-industrial-service b{display:block;margin-top:2px;font-size:10px}.cc-industrial-service span{display:block;margin-top:2px;color:#c0cfdb;font-size:7px}
 @media(max-width:980px){.cc-industrial-services{grid-template-columns:repeat(3,minmax(0,1fr))}.cc-industrial-hero{grid-template-columns:minmax(0,1.1fr) minmax(280px,.9fr)}}
 @media(max-width:720px){.cc-industrial-hero{display:block}.cc-industrial-copy{padding:24px 20px 20px}.cc-industrial-home .cc-industrial-title{font-size:36px!important}.cc-industrial-art{min-height:195px}.cc-industrial-services{grid-template-columns:repeat(2,minmax(0,1fr))}.cc-industrial-service{min-height:98px}}
 `;document.head.appendChild(s);
}
function known(target){const m={projects:'projects',budget:'budget',audit:'audit',reports:'reports'};const el=m[target]?document.querySelector(`#ccxNav [data-ccx="${m[target]}"]`):null;if(el){el.click();return true}return false}
function label(name){const n=norm(name),els=[...document.querySelectorAll('button,a,[role="button"],[data-tab],[data-nav]')];const el=els.find(x=>!x.closest('[data-cc-industrial-home]')&&x.offsetParent!==null&&norm(x.textContent||'')===n)||els.find(x=>!x.closest('[data-cc-industrial-home]')&&x.offsetParent!==null&&norm(x.textContent||'').includes(n));if(el){el.click();return true}return false}
function go(t){if(known(t))return;if(t==='engineering'&&label('Ingeniería'))return;if(t==='supervision'&&(label('Supervisión')||label('Visitas')))return;if(t==='contracts'&&(label('Contratos')||label('Contrato')))return;known('projects')}
function card(target,kicker,title,subtitle,img){return `<button class="cc-industrial-service" data-go="${target}" style="--cc-service-img:url('${img}')"><div><small>${kicker}</small><b>${title}</b><span>${subtitle}</span></div></button>`}
function markup(){return `<section class="cc-industrial-home" data-cc-industrial-home><div class="cc-industrial-hero"><div class="cc-industrial-copy"><span class="cc-industrial-kicker">ZORDON · CONTROL CONTRACTUAL + INGENIERÍA</span><h1 class="cc-industrial-title"><span>Tu proyecto.</span><em>Control total.</em></h1><p>Proyectos, ingeniería, supervisión, costos, contratos y auditoría con una identidad visual centrada en obra y construcción.</p><div class="cc-industrial-actions"><button type="button" class="primary" data-go="projects">Ver proyectos</button><button type="button" data-go="engineering">Abrir Ingeniería</button></div></div><div class="cc-industrial-art" style="--cc-hero-img:url('${IMG.hero}')"><div class="cc-industrial-badge"><b>CONTROL DE PROYECTOS</b><span>Ingeniería · obra · contratos · seguimiento</span></div></div></div><div class="cc-industrial-services">${card('projects','Gestión','Proyectos','Expedientes y avance',IMG.projects)}${card('engineering','Técnico','Ingeniería','Cálculo y diseño',IMG.engineering)}${card('supervision','Campo','Supervisión','Visitas y seguridad',IMG.supervision)}${card('audit','Control','Auditoría','Hallazgos y calidad',IMG.audit)}${card('budget','Costos','Presupuestos','Cantidades y estimaciones',IMG.budget)}${card('contracts','Contractual','Contratos','Plazos y garantías',IMG.contracts)}</div></section>`}
function mount(){css();const root=document.querySelector('#content .ccx-page'),title=root?.querySelector('.ccx-head h2');if(!root||!title||!/estado general del portafolio/i.test(title.textContent||''))return false;const old=root.querySelector('[data-cc-industrial-home]');if(old)old.remove();const box=document.createElement('div');box.innerHTML=markup();const hero=box.firstElementChild;const anchor=root.querySelector('.ccx-kpis')||root.firstElementChild;if(anchor)anchor.insertAdjacentElement('beforebegin',hero);else root.prepend(hero);hero.addEventListener('click',e=>{const b=e.target.closest('[data-go]');if(b)go(b.dataset.go)});return true}
let queued=false;const run=()=>{queued=false;mount()};new MutationObserver(()=>{if(queued)return;queued=true;(typeof requestAnimationFrame==='function'?requestAnimationFrame:setTimeout)(run)}).observe(document.documentElement,{childList:true,subtree:true});setTimeout(run,0);setTimeout(run,450);setTimeout(run,1200);window.__ccIndustrialHome={run,go};
})();