import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.57.0";
import jpeg from "npm:jpeg-js@0.4.4";
const U=Deno.env.get("SUPABASE_URL")??"",K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??"",T=Deno.env.get("TELEGRAM_BOT_TOKEN")??"",db=createClient(U,K,{auth:{persistSession:false,autoRefreshToken:false}});
const json=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{"content-type":"application/json","cache-control":"no-store"}}),clean=(v:any,n=300)=>String(v??"").replace(/[\u0000-\u001f\u007f]/g," ").trim().slice(0,n);
async function sha(v:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return[...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join("")}
function fromB64(s:string){const bin=atob(s),out=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)out[i]=bin.charCodeAt(i);return out}
function toB64(bytes:Uint8Array){let s="";for(let i=0;i<bytes.length;i+=32768)s+=String.fromCharCode(...bytes.subarray(i,Math.min(i+32768,bytes.length)));return btoa(s)}
function parseDataUrl(src:any){const s=String(src||""),m=s.match(/^data:image\/(jpeg|jpg);base64,(.+)$/i);if(!m)return null;try{return fromB64(m[2])}catch{return null}}
function completeJpeg(b:Uint8Array){return b.length>300&&b[0]===0xff&&b[1]===0xd8&&b[b.length-2]===0xff&&b[b.length-1]===0xd9}
function suspiciousGray(decoded:any){const w=Number(decoded?.width||0),h=Number(decoded?.height||0),d=decoded?.data;if(!w||!h||!d)return true;const xs=Math.max(1,Math.floor(w/160)),ys=Math.max(1,Math.floor(h/120));let total=0,neutral=0,run=0,maxRun=0;for(let y=Math.floor(h*.12);y<h;y+=ys){let row=0,rowNeutral=0;for(let x=0;x<w;x+=xs){const i=(y*w+x)*4,r=d[i],g=d[i+1],b=d[i+2];row++;total++;const isNeutral=Math.abs(r-g)<=3&&Math.abs(g-b)<=3&&r>=116&&r<=142;if(isNeutral){rowNeutral++;neutral++}}const ratio=row?rowNeutral/row:0;if(ratio>=.82){run++;maxRun=Math.max(maxRun,run)}else run=0}return(total?neutral/total:1)>.28||maxRun*ys>=Math.max(10,Math.floor(h*.08))}
function sanitize(bytes:Uint8Array){if(!completeJpeg(bytes))return{ok:false,error:"JPEG incompleto"};try{const dec=jpeg.decode(bytes,{useTArray:true,formatAsRGBA:true,tolerantDecoding:false,maxResolutionInMP:25,maxMemoryUsageInMB:256} as any);if(!dec?.width||!dec?.height)return{ok:false,error:"No se pudo decodificar"};if(suspiciousGray(dec))return{ok:false,error:"Se detectaron bloques o relleno anormal en la imagen"};const enc=jpeg.encode({data:dec.data,width:dec.width,height:dec.height},90).data as Uint8Array;return{ok:true,bytes:new Uint8Array(enc),width:dec.width,height:dec.height}}catch(e){return{ok:false,error:clean(e instanceof Error?e.message:e,180)||"Error de decodificación"}}}
Deno.serve(async req=>{try{if(req.method==="GET")return json({ok:true,service:"visit-image-sanitizer",version:"1.2-strict-missing-photo"});if(req.method!=="POST")return json({error:"method"},405);if((req.headers.get("x-internal-image-secret")??"")!==await sha(T))return json({error:"unauthorized"},401);const body=await req.json().catch(()=>({})),visitId=clean(body?.visit_id,100);if(!visitId)return json({error:"visit_id required"},400);const {data:v,error}=await db.from("visits").select("id,raw_data").eq("id",visitId).maybeSingle();if(error)throw error;if(!v)return json({error:"visit not found"},404);const raw={...(v.raw_data||{})},photos=Array.isArray(raw.photos)?raw.photos:[];let valid=0,rejected=0,changed=0;const next:any[]=[];for(const p0 of photos){const p={...(p0||{})},src=String(p.src||"");if(!src){rejected++;if(p.status!=="requiere_recarga"||!p.integrityCheckedAt){p.status="requiere_recarga";p.integrityError=p.integrityError||"Fotografía sin archivo válido disponible";p.integrityCheckedAt=new Date().toISOString();changed++}next.push(p);continue}if(String(p.status||"").toLowerCase()==="integrada"&&p.integrityCheckedAt){valid++;next.push(p);continue}const bytes=parseDataUrl(src);if(!bytes){p.corruptSrcBackup=p.corruptSrcBackup||src;p.src="";p.status="requiere_recarga";p.integrityError="Formato de imagen no válido";p.integrityCheckedAt=new Date().toISOString();rejected++;changed++;next.push(p);continue}const s=sanitize(bytes);if(!s.ok){p.corruptSrcBackup=p.corruptSrcBackup||src;p.src="";p.status="requiere_recarga";p.integrityError=s.error;p.integrityCheckedAt=new Date().toISOString();rejected++;changed++;next.push(p);continue}p.src=`data:image/jpeg;base64,${toB64(s.bytes!)}`;p.status="integrada";p.width=s.width;p.height=s.height;p.integrityError=null;p.integrityCheckedAt=new Date().toISOString();valid++;changed++;next.push(p)}raw.photos=next;raw.photoCount=Number(raw.photoCount||photos.length||0);raw.reportPhotoCount=valid;raw.photoIntegrityNote=rejected?`Se detectaron ${rejected} fotografía(s) dañada(s), incompleta(s) o sin archivo; fueron excluidas del informe hasta su recarga.`:"Todas las fotografías incluidas superaron la validación de integridad antes de generar el informe.";raw.photoIntegrityCheckedAt=new Date().toISOString();if(changed||raw.reportPhotoCount!==v.raw_data?.reportPhotoCount||raw.photoIntegrityNote!==v.raw_data?.photoIntegrityNote){const {error:u}=await db.from("visits").update({raw_data:raw,updated_at:new Date().toISOString()}).eq("id",visitId);if(u)throw u}return json({ok:true,visit_id:visitId,registered:photos.length,valid,rejected,changed,note:raw.photoIntegrityNote})}catch(e){console.error("visit-image-sanitizer",e);return json({ok:false,error:clean(e instanceof Error?e.message:e,500)},500)}});