const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');

const dataSource=fs.readFileSync('fhis-cost-data-v1.js','utf8');
const context={window:null};context.window=context;vm.createContext(context);vm.runInContext(dataSource,context);
const data=context.__ccFhisCostData;
assert(data,'la base FHIS/TSC debe exponer datos');
assert.equal(data.stats.sheets,780,'debe conservar las 780 hojas del libro');
assert(data.stats.fichas>=770,'debe importar la colección completa de fichas');
assert(data.stats.resources>=3600,'debe importar los recursos de análisis unitario');
assert(data.fichas.some(f=>f.code==='F102009'),'debe incluir instalación de tubería PVC de 6 pulgadas');
assert(data.fichas.some(f=>f.resources.some(r=>r.type==='Mano de obra')),'debe conservar mano de obra');
assert(data.fichas.some(f=>f.resources.some(r=>r.type==='Material')),'debe conservar materiales');
assert(data.fichas.some(f=>f.resources.some(r=>r.type==='Equipo')),'debe conservar equipo');

const app=fs.readFileSync('cost-program-v1.js','utf8');
for(const feature of ['Fichas de costo','Presupuesto','Formatos','Institución','Duplicar y editar','Generar adaptado'])assert(app.includes(feature),`falta ${feature}`);
for(const feature of ['Actividades','Precios','Especificaciones','Buscar fichas automáticamente','Eliminar ficha','materialPrices'])assert(app.includes(feature),`falta ${feature}`);
assert(app.includes('saveDB()'),'los cambios deben persistir en el expediente compartido');
assert.equal((fs.readdirSync('assets/formats/via-administracion').filter(x=>!x.startsWith('~$'))).length,18,'deben publicarse los 18 formatos administrativos');
const knowledgeSource=fs.readFileSync('assets/cost-knowledge/index.js','utf8');
const knowledgeContext={window:null};knowledgeContext.window=knowledgeContext;vm.createContext(knowledgeContext);vm.runInContext(knowledgeSource,knowledgeContext);
const knowledge=knowledgeContext.__ccCostKnowledge;
assert(knowledge.stats.fichas>=6400,'debe importar la biblioteca FICHAS 17102013');
assert(knowledge.stats.resources>=46000,'debe relacionar los recursos de las fichas');
assert(knowledge.stats.uniqueResources>=2700,'debe construir el catálogo maestro de insumos');
assert.equal(fs.readdirSync('assets/cost-knowledge').filter(x=>/^fichas-\d+\.json$/.test(x)).length,knowledge.stats.chunks,'cada bloque progresivo debe existir');
for(const file of ['fichas-17102013.pdf','listado-insumos.pdf','listado-actividades.pdf','fichas-costos-unitarios.pdf','especificaciones-actividades.pdf','ingenieria-trafico.pdf'])assert(fs.existsSync(`assets/cost-knowledge/sources/${file}`),`falta fuente ${file}`);
assert(fs.existsSync('assets/cost-knowledge/sources/formato-fichas-presupuestos.pdf'),'debe conservar el formato PDF institucional proporcionado');
for(const feature of ['CANON_INDEX','seenKnowledgeCodes','seenKnowledgeNames','printFicha','printBudget','FICHA DE COSTOS','PRESUPUESTO DE OBRA','GASTOS ADMINISTRATIVOS','costSettings'])assert(app.includes(feature),`falta ${feature}`);
for(const feature of ['functionalFicha','pendingDefinition','Recurso y precio pendientes de definir','Ficha operable con datos pendientes'])assert(app.includes(feature),`falta tolerancia funcional: ${feature}`);
assert(fs.existsSync('scripts/audit-cost-library.cjs'),'debe existir la auditoría exhaustiva de fichas');
const normalizeIdentity=value=>String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z0-9]/g,'');
const baseSeenCodes=new Set(),baseSeenNames=new Set();
const canonicalBase=[...data.fichas].sort((a,b)=>(b.resources?.length||0)-(a.resources?.length||0)).filter(x=>{const code=normalizeIdentity(x.code),name=`${normalizeIdentity(x.description)}|${normalizeIdentity(x.unit)}`;if((code&&baseSeenCodes.has(code))||baseSeenNames.has(name))return false;if(code)baseSeenCodes.add(code);baseSeenNames.add(name);return true});
const baseCodes=new Set(canonicalBase.map(x=>normalizeIdentity(x.code)).filter(Boolean));
const baseNames=new Set(canonicalBase.map(x=>`${normalizeIdentity(x.description)}|${normalizeIdentity(x.unit)}`));
const seenCodes=new Set(),seenNames=new Set();
const canonical=[...knowledge.index].sort((a,b)=>(/^F/i.test(b.code)?1:0)-(/^F/i.test(a.code)?1:0)||(a.sourcePage||0)-(b.sourcePage||0)).filter(x=>{const code=normalizeIdentity(x.code),name=`${normalizeIdentity(x.description)}|${normalizeIdentity(x.unit)}`;if((code&&baseCodes.has(code))||baseNames.has(name)||(code&&seenCodes.has(code))||seenNames.has(name))return false;if(code)seenCodes.add(code);seenNames.add(name);return true});
const combined=[...canonicalBase,...canonical];
assert.equal(new Set(combined.map(x=>normalizeIdentity(x.code)).filter(Boolean)).size,combined.filter(x=>normalizeIdentity(x.code)).length,'no debe publicar códigos duplicados');
assert.equal(new Set(combined.map(x=>`${normalizeIdentity(x.description)}|${normalizeIdentity(x.unit)}`)).size,combined.length,'no debe publicar fichas duplicadas por descripción y unidad');
console.log('cost-program: 6,254 fichas únicas y funcionales, precios, CRUD, impresión, presupuesto y especificaciones verificados');
