const assert=require('node:assert/strict');
const fs=require('node:fs');

const src=fs.readFileSync('halu-avatar-motion-v1.js','utf8');
assert.match(src,/cc-halu-moving/,'incluye animación de desplazamiento');
assert.match(src,/ccHaluWalk/,'simula pasos al cambiar de posición');
assert.match(src,/cc-halu-gesture/,'incluye gesto al llegar');
assert.match(src,/placeNext/,'permite marcar una posición con un toque');
assert.match(src,/localStorage\.setItem\(KEY/,'conserva la posición entre sesiones');
assert.match(src,/scrollIntoView/,'puede buscar y señalar controles visibles');
assert.match(src,/no te veo\|no estas visible/,'responde a órdenes de aparición');
assert.match(src,/window\.__ccHaluAvatar/,'expone el controlador al chat');
assert.match(src,/pointerdown/,'permite arrastrar el avatar con mouse o toque');
assert.match(src,/setPointerCapture/,'mantiene el arrastre fuera del avatar');
assert.match(src,/ArrowLeft/,'permite mover el avatar con teclado');
assert.match(src,/function roam/,'permite recorrido autónomo por la pantalla');
assert.match(src,/const r=el\.getBoundingClientRect\(\);moveTo/,'recalcula el destino después del desplazamiento');
assert.match(src,/chat\?\.classList\.remove\('open'\);roam\(true\)/,'cierra el dialogo antes de iniciar el recorrido');
assert.match(src,/ccHaluLegLeft/,'alterna el movimiento del pie izquierdo');
assert.match(src,/ccHaluLegRight/,'alterna el movimiento del pie derecho');
assert.match(src,/e\.clientX-r\.width\/2,e\.clientY-r\.height\/2/,'centra el avatar grande en el punto elegido');
console.log('halu-avatar-motion: 17 verificaciones superadas');
