import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.57.0";
import { generateReportFiles, reportLabel } from "./report.ts";

const supabaseUrl=Deno.env.get("SUPABASE_URL")??"";
const serviceKey=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??"";
const telegramToken=Deno.env.get("TELEGRAM_BOT_TOKEN")??"";
const geminiKey=Deno.env.get("GEMINI_API_KEY")??"";
const geminiModel=Deno.env.get("GEMINI_MODEL")??"gemini-3.6-flash";
const admin=createClient(supabaseUrl,serviceKey,{auth:{persistSession:false,autoRefreshToken:false}});

const clean=(v:any,max=5000)=>String(v??"").replace(/[\u0000-\u001f\u007f]/g," ").trim().slice(0,max);
const norm=(v:any)=>String(v??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9ñ]+/g," ").replace(/\s+/g," ").trim();
const json=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"}});
const todayHN=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"America/Tegucigalpa",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
const safe=(v:string)=>clean(v,100).normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-zA-Z0-9._-]+/g,"_").replace(/^_+|_+$/g,"")||"archivo";
async function sha256(v:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return Array.from(new Uint8Array(d)).map(b=>b.toString(16).padStart(2,"0")).join("")}
function b64(bytes:Uint8Array){let s="";for(let i=0;i<bytes.length;i+=32768)s+=String.fromCharCode(...bytes.subarray(i,Math.min(i+32768,bytes.length)));return btoa(s)}

async function tg(method:string,body:Record<string,any>){const r=await fetch(`https://api.telegram.org/bot${telegramToken}/${method}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(!r.ok||d?.ok===false)throw new Error(d?.description||`Telegram ${r.status}`);return d}
const send=(chat:any,text:string,markup?:any)=>tg("sendMessage",{chat_id:chat,text:clean(text,3900),disable_web_page_preview:true,...(markup?{reply_markup:markup}:{})});
async function sendLong(chat:any,text:string){let part="";for(const line of String(text).split("\n")){const next=part?part+"\n"+line:line;if(next.length>3500){if(part)await send(chat,part);part=line}else part=next}if(part)await send(chat,part)}
async function sendDoc(chat:any,bytes:Uint8Array,fileName:string,mime:string,caption:string){const fd=new FormData();fd.append("chat_id",String(chat));fd.append("caption",clean(caption,900));fd.append("document",new Blob([bytes],{type:mime}),fileName);const r=await fetch(`https://api.telegram.org/bot${telegramToken}/sendDocument`,{method:"POST",body:fd});const d=await r.json();if(!r.ok||d?.ok===false)throw new Error(d?.description||`Telegram document ${r.status}`);return d}

function mtype(m:any){if(m?.voice)return"voice";if(m?.audio)return"audio";if(m?.photo)return"photo";if(m?.document)return"document";if(m?.location)return"location";if(m?.text?.startsWith("/"))return"command";return m?.text||m?.caption?"text":"other"}
function finfo(m:any){if(m?.voice)return{id:m.voice.file_id,unique:m.voice.file_unique_id,mime:m.voice.mime_type||"audio/ogg",name:`voice_${m.message_id}.ogg`};if(m?.audio)return{id:m.audio.file_id,unique:m.audio.file_unique_id,mime:m.audio.mime_type||"audio/mpeg",name:m.audio.file_name||`audio_${m.message_id}.mp3`};if(m?.document)return{id:m.document.file_id,unique:m.document.file_unique_id,mime:m.document.mime_type||"application/octet-stream",name:m.document.file_name||`document_${m.message_id}`};if(Array.isArray(m?.photo)&&m.photo.length){const p=m.photo[m.photo.length-1];return{id:p.file_id,unique:p.file_unique_id,mime:"image/jpeg",name:`photo_${m.message_id}.jpg`}}return{id:null,unique:null,mime:null,name:null}}
async function downloadTG(fileId:string){const meta=await tg("getFile",{file_id:fileId});const path=meta?.result?.file_path;if(!path)throw new Error("Telegram no devolvió file_path");const r=await fetch(`https://api.telegram.org/file/bot${telegramToken}/${path}`);if(!r.ok)throw new Error(`No se pudo descargar archivo (${r.status})`);const bytes=new Uint8Array(await r.arrayBuffer());if(bytes.byteLength>15*1024*1024)throw new Error("El archivo supera 15 MB");return{bytes,path,size:bytes.byteLength}}

async function catalog(workspace:string){const [{data:p,error:pe},{data:a,error:ae}]=await Promise.all([admin.from("projects").select("id,code,name,description,location,status,budget_estimate,start_date,end_date,execution_days,raw_data").eq("workspace_id",workspace).is("archived_at",null).order("name").limit(500),admin.from("project_aliases").select("project_id,alias_value").eq("workspace_id",workspace).limit(1500)]);if(pe)throw pe;if(ae)console.error("aliases",ae.message);const map=new Map<string,any>();for(const x of p||[])map.set(x.id,{...x,aliases:[]});for(const x of a||[]){const q=map.get(x.project_id);if(q)q.aliases.push(x.alias_value)}return[...map.values()]}
const stop=new Set(["genera","generar","crea","crear","prepara","preparar","haz","hacer","informe","reporte","documento","visita","visitas","con","las","los","del","de","la","el","que","acabo","mandar","mande","enviar","envie","fotos","foto","fotografias","fotografia","audio","audios","proyecto","para","por","favor","quiero","un","una","y","hoy","sobre"]);
function tokens(q:string){return norm(q).split(" ").filter(t=>t.length>=3&&!stop.has(t))}
function score(p:any,q:string){const nq=norm(q),ts=tokens(q),hay=norm([p.code,p.name,p.location,p.status,...(p.aliases||[])].join(" "));let s=0;if(p.code&&nq.includes(norm(p.code)))s+=180;for(const a of p.aliases||[])if(norm(a).length>3&&nq.includes(norm(a)))s+=140;for(const t of ts){if(hay.includes(t))s+=14;if(norm(p.name).includes(t))s+=7}if(ts.length>=2&&ts.every(t=>hay.includes(t)))s+=60;return s}
function ranked(list:any[],q:string,n=8){return list.map(p=>({p,s:score(p,q)})).filter(x=>x.s>0).sort((a,b)=>b.s-a.s).slice(0,n)}
function resolveStrict(list:any[],q:string){const r=ranked(list,q,3);if(!r.length)return null;const a=r[0],b=r[1];return a.s>=45&&(!b||a.s>=b.s+15||a.s>=b.s*1.25)?a.p:null}
function line(p:any){return`${p.code?`${p.code} · `:""}${p.name}${p.status?` — ${p.status}`:""}`}

function extractInteractionText(d:any){const out:string[]=[];const add=(v:any)=>{if(typeof v==="string"&&v.trim())out.push(v.trim())};add(d?.output_text);if(Array.isArray(d?.output))for(const x of d.output){add(x?.text);for(const c of x?.content||[])add(c?.text)}if(Array.isArray(d?.steps))for(const s of d.steps){for(const m of[s?.model_output,s?.output,s]){add(m?.text);add(m?.output_text);for(const c of m?.content||[]){add(c?.text);for(const p of c?.parts||[])add(p?.text)}}}return[...new Set(out)].join("\n").trim()}
async function gemini(input:any){if(!geminiKey)throw new Error("GEMINI_API_KEY no disponible");const r=await fetch("https://generativelanguage.googleapis.com/v1beta/interactions",{method:"POST",headers:{"content-type":"application/json","x-goog-api-key":geminiKey,"Api-Revision":"2026-05-20"},body:JSON.stringify({model:geminiModel,input})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(clean(d?.error?.message||`Gemini ${r.status}`,700));return d}
function parseJSON(t:string){try{let s=t.trim().replace(/^```(?:json)?\s*/i,"").replace(/\s*```$/i,"");const a=s.indexOf("{"),b=s.lastIndexOf("}");if(a>=0&&b>a)s=s.slice(a,b+1);return JSON.parse(s)}catch{return null}}

async function projectContext(projectId:string){const [p,c,v,b,g,pay,e]=await Promise.all([admin.from("projects").select("id,code,name,description,location,status,budget_estimate,start_date,end_date,execution_days").eq("id",projectId).maybeSingle(),admin.from("contracts").select("number,contractor,original_amount,start_date,end_date,execution_days,status,advance_paid,notes").eq("project_id",projectId).is("voided_at",null),admin.from("visits").select("visit_number,visit_date,inspector,summary,raw_data").eq("project_id",projectId).is("voided_at",null).order("visit_date",{ascending:false}).limit(10),admin.from("project_budgets").select("initial_assignment,base_paid,source,cut_date").eq("project_id",projectId).maybeSingle(),admin.from("guarantees").select("guarantee_type,number,end_date,applied_amount").eq("project_id",projectId).is("voided_at",null),admin.from("payments").select("movement_type,amount,payment_date,status").eq("project_id",projectId).is("voided_at",null).order("payment_date",{ascending:false}).limit(10),admin.from("estimates").select("number,period_start,period_end,gross,net,status").eq("project_id",projectId).is("voided_at",null).order("number")]);return JSON.stringify({project:p.data,contracts:c.data||[],visits:v.data||[],budget:b.data,guarantees:g.data||[],payments:pay.data||[],estimates:e.data||[]}).slice(0,20000)}
async function analyzeMedia(bytes:Uint8Array,mime:string,type:string,caption:string,project:any|null,list:any[]){const ctx=project?await projectContext(project.id):"SIN PROYECTO ACTIVO";const cat=list.map(p=>`${p.code}|${p.name}|${(p.aliases||[]).join(";")}`).join("\n").slice(0,12000);const prompt=`Eres el Ingeniero multimodal de Control Contractual. Analiza el archivo recibido. Proyecto activo: ${project?line(project):"No definido"}. Expediente: ${ctx}. Catalogo: ${cat}. Orden: ${caption||"Analiza y guarda como evidencia"}. Devuelve SOLO JSON valido: {"transcript":"","project_query":"","intent":"query|register_visit|add_report|add_evidence|analyze_document","summary":"","observations":[],"recommendations":[],"risks":[],"report_type":"visit|technical|contractual|general","report_section":"visita|avance|observaciones|recomendaciones|documentacion|general","report_text":"","visit_date":"YYYY-MM-DD o vacio","physical_progress":null,"confidence":0.0}. No inventes datos. En foto describe solo visible. En audio transcribe y entiende la orden. En documentos extrae datos verificables.`;const mediaType=type==="photo"?"image":type==="voice"||type==="audio"?"audio":"document";const d=await gemini([{type:"text",text:prompt},{type:mediaType,data:b64(bytes),mime_type:mime}]);const p=parseJSON(extractInteractionText(d));if(!p)throw new Error("La IA no devolvió análisis estructurado");return p}

function reportType(text:string){const n=norm(text);if(/visita|supervision|campo/.test(n))return"visitas";if(/financier/.test(n))return"financiero";if(/contractual|contrato/.test(n))return"contractual";if(/estimacion|pago/.test(n))return"estimaciones";if(/garantia/.test(n))return"garantias";if(/adjudic|oferta|cierre/.test(n))return"adjudicacion";if(/recepcion/.test(n))return"recepcion";if(/liquidacion/.test(n))return"liquidacion";if(/integral|completo/.test(n))return"integral";return"general"}
function isReportRequest(text:string){const n=norm(text);return/(genera|generar|crea|crear|prepara|preparar|haz|hacer|necesito|quiero)/.test(n)&&/(informe|reporte|documento|acta|liquidacion|estimacion)/.test(n)}
function formatKeyboard(id:string){return{inline_keyboard:[[{text:"📄 PDF",callback_data:`rf:${id}:pdf`},{text:"📝 Word",callback_data:`rf:${id}:docx`}],[{text:"📄📝 PDF + Word",callback_data:`rf:${id}:both`}],[{text:"❌ Cancelar",callback_data:`cancel:${id}`}]]}}

async function visitsFor(projectId:string){const {data,error}=await admin.from("visits").select("visit_number,visit_date,inspector,summary,raw_data").eq("project_id",projectId).is("voided_at",null).order("visit_date",{ascending:false}).order("visit_number",{ascending:false}).limit(25);if(error)throw error;return data||[]}
function visitDesc(v:any){const raw=v.raw_data||{};const s=clean(raw.objective||raw.activities||v.summary||"Visita de supervisión",95);return`Visita N.º ${v.visit_number} · ${v.visit_date}${s?` — ${s}`:""}`}
function visitKeyboard(id:string,visits:any[]){const rows=visits.slice(0,20).map(v=>[{text:`📍 N.º ${v.visit_number} · ${v.visit_date}`,callback_data:`rv:${id}:${v.visit_number}`}]);rows.push([{text:"📚 Todas las visitas",callback_data:`rv:${id}:all`}]);rows.push([{text:"❌ Cancelar",callback_data:`cancel:${id}`}]);return{inline_keyboard:rows}}
async function askVisit(chat:any,id:string,project:any){const visits=await visitsFor(project.id);if(!visits.length){await send(chat,"Este proyecto todavía no tiene visitas registradas. Puedes enviarme la información, fotos o audio de la visita y primero la registramos.");return false}const list=visits.map((v:any)=>`• ${visitDesc(v)}`).join("\n");await send(chat,`📍 ¿Qué visita deseas incluir en el informe?\n\n${list}\n\nTambién puedes generar todas las visitas.`,visitKeyboard(id,visits));return true}

async function recoverRecentEvidence(link:any,project:any,list:any[],minutes=120){const since=new Date(Date.now()-minutes*60000).toISOString();const {data:inb}=await admin.from("assistant_inbox").select("id,message_type,telegram_file_id,telegram_file_unique_id,mime_type,text_content,received_at").eq("telegram_link_id",link.id).in("message_type",["photo","voice","audio","document"]).gte("received_at",since).order("received_at");const result:any[]=[];for(const row of inb||[]){const {data:existing}=await admin.from("project_evidence").select("*").eq("inbox_id",row.id).maybeSingle();if(existing){if(existing.project_id&&existing.project_id!==project.id)continue;if(!existing.project_id)await admin.from("project_evidence").update({project_id:project.id}).eq("id",existing.id);result.push({...existing,project_id:project.id});continue}if(!row.telegram_file_id)continue;try{const dl=await downloadTG(row.telegram_file_id);const ext=row.message_type==="photo"?"jpg":row.message_type==="voice"?"ogg":row.message_type==="audio"?"mp3":"bin";const name=`recovered_${row.id}.${ext}`;const path=`${link.workspace_id}/${project.id}/${todayHN()}/${Date.now()}_${safe(name)}`;const up=await admin.storage.from("telegram-evidence").upload(path,dl.bytes,{contentType:row.mime_type||"application/octet-stream",upsert:false});if(up.error)throw up.error;const a=await analyzeMedia(dl.bytes,row.mime_type||"application/octet-stream",row.message_type,row.text_content||"",project,list);const {data:e,error}=await admin.from("project_evidence").insert({workspace_id:link.workspace_id,project_id:project.id,inbox_id:row.id,evidence_type:row.message_type,storage_path:path,mime_type:row.mime_type,file_name:name,size_bytes:dl.size,telegram_file_unique_id:row.telegram_file_unique_id,extracted_text:a.transcript||a.summary||null,analysis:a,created_by:link.user_id}).select("*").single();if(error)throw error;await admin.from("assistant_inbox").update({project_id:project.id,status:"processed",processed_at:new Date().toISOString()}).eq("id",row.id);result.push(e)}catch(e){console.error("recover evidence",row.id,clean(e instanceof Error?e.message:e,300))}}return result}
async function recentTextContext(link:any,projectId:string,currentText:string,minutes=120){const since=new Date(Date.now()-minutes*60000).toISOString();const {data}=await admin.from("assistant_inbox").select("message_type,text_content,project_id,received_at").eq("telegram_link_id",link.id).gte("received_at",since).order("received_at",{ascending:false}).limit(18);const arr=(data||[]).filter((x:any)=>x.text_content&&x.text_content!==currentText&&["text","command","photo","voice","audio","document"].includes(x.message_type)&&(x.project_id===projectId||!x.project_id)).reverse().map((x:any)=>clean(x.text_content,700)).filter(Boolean);return[...new Set(arr)].slice(-10).join("\n")}
async function createReportDraft(link:any,project:any,text:string,type:string,list:any[]){const recent=await recoverRecentEvidence(link,project,list,120);const contextText=await recentTextContext(link,project.id,text,120);const ids=recent.map((x:any)=>x.id);const {data:d,error}=await admin.from("assistant_drafts").insert({workspace_id:link.workspace_id,project_id:project.id,draft_type:"generate_report",title:`${reportLabel(type)} · ${project.code}`,source_text:text,summary:"Solicitud de generación de documento desde Telegram",parsed_data:{report_type:type,evidence_ids:ids,request_text:text,context_text:contextText,visit_selection:null},status:"draft",created_by:link.user_id}).select("id").single();if(error)throw error;await admin.from("telegram_links").update({current_project_id:project.id,updated_at:new Date().toISOString()}).eq("id",link.id);return{draftId:d.id,evidence:recent,contextText}}

async function generateAndSend(chat:any,link:any,draft:any,format:string){const pd=draft.parsed_data||{},type=pd.report_type||"general";const result=await generateReportFiles({admin,projectId:draft.project_id,reportType:type,evidenceIds:pd.evidence_ids||[],requestText:pd.request_text||"",contextText:pd.context_text||"",visitSelection:pd.visit_selection||null});const outputs=result.outputs.filter((o:any)=>format==="both"||o.fmt===format);for(const o of outputs){const path=`${link.workspace_id}/${draft.project_id}/reports/${todayHN()}/${Date.now()}_${o.name}`;const {error}=await admin.storage.from("project-files").upload(path,o.bytes,{contentType:o.mime,upsert:false});if(error)throw error;await admin.from("generated_reports").insert({workspace_id:link.workspace_id,project_id:draft.project_id,requested_by:link.user_id,source_draft_id:draft.id,report_type:type,title:result.title,format:o.fmt,storage_path:path,mime_type:o.mime,file_name:o.name,size_bytes:o.bytes.byteLength,evidence_count:result.evidenceCount,metadata:{request_text:pd.request_text||"",evidence_ids:pd.evidence_ids||[],visit_selection:pd.visit_selection||null,visit_numbers:(result.selectedVisits||[]).map((v:any)=>v.visit_number),photo_count:result.photoCount,template:type==="visitas"?"visita_supervision_v3":"professional_general_v2"}});await sendDoc(chat,o.bytes,o.name,o.mime,`${result.title}\n${result.project.code} · ${result.project.name}`)}await admin.from("assistant_drafts").update({status:"applied",approved_by:link.user_id,approved_at:new Date().toISOString(),applied_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",draft.id);return{count:outputs.length,photoCount:result.photoCount,visits:result.selectedVisits||[]}}

async function approveDraft(id:string,link:any){const {data:d}=await admin.from("assistant_drafts").select("*").eq("id",id).eq("workspace_id",link.workspace_id).maybeSingle();if(!d)throw new Error("Borrador no encontrado");if(d.status==="applied")return"Este borrador ya fue aplicado.";const a=d.parsed_data||{},pid=d.project_id;if(!pid)throw new Error("Borrador sin proyecto");if(d.draft_type==="visit"){const {data:last}=await admin.from("visits").select("visit_number").eq("project_id",pid).is("voided_at",null).order("visit_number",{ascending:false}).limit(1).maybeSingle();const num=(Number(last?.visit_number)||0)+1,date=/^\d{4}-\d{2}-\d{2}$/.test(a.visit_date||"")?a.visit_date:todayHN(),vid=crypto.randomUUID();const raw={id:vid,projectId:pid,number:num,date,type:"Supervisión",status:"En seguimiento",summary:a.report_text||a.summary||"Visita registrada desde Telegram",generalObservations:a.report_text||a.summary||"",observations:a.observations||[],instructions:(a.recommendations||[]).join(" "),source:"Telegram · Ingeniero IA"};const {error}=await admin.from("visits").insert({id:vid,workspace_id:link.workspace_id,project_id:pid,visit_number:num,visit_date:date,summary:raw.summary,raw_data:raw});if(error)throw error;await admin.from("assistant_drafts").update({status:"applied",approved_by:link.user_id,approved_at:new Date().toISOString(),applied_at:new Date().toISOString()}).eq("id",d.id);return`✅ Visita N.º ${num} registrada y sincronizada con Control Contractual.`}await admin.from("project_report_inputs").insert({workspace_id:link.workspace_id,project_id:pid,source_inbox_id:d.inbox_id,report_type:a.report_type||"general",section:a.report_section||"observaciones",content:a.report_text||a.summary||d.summary||"Información desde Telegram",structured_data:a,status:"approved",created_by:link.user_id,approved_by:link.user_id,approved_at:new Date().toISOString()});await admin.from("assistant_drafts").update({status:"applied",approved_by:link.user_id,approved_at:new Date().toISOString(),applied_at:new Date().toISOString()}).eq("id",d.id);return"✅ Información aprobada y agregada al expediente."}

async function handleCallback(u:any,link:any,chat:any){const cq=u.callback_query,data=clean(cq.data,100);await tg("answerCallbackQuery",{callback_query_id:cq.id,text:"Procesando..."});const [action,id,arg]=data.split(":");if(action==="cancel"){await admin.from("assistant_drafts").update({status:"rejected",updated_at:new Date().toISOString()}).eq("id",id).eq("workspace_id",link.workspace_id);await send(chat,"❌ Operación cancelada. No se modificó el expediente.");return}
 if(action==="rt"){const {data:d}=await admin.from("assistant_drafts").select("parsed_data,project_id").eq("id",id).maybeSingle();if(!d)return;await admin.from("assistant_drafts").update({parsed_data:{...(d.parsed_data||{}),report_type:arg},title:reportLabel(arg),updated_at:new Date().toISOString()}).eq("id",id);const {data:p}=await admin.from("projects").select("id,code,name").eq("id",d.project_id).maybeSingle();if(arg==="visitas"&&p){await askVisit(chat,id,p);return}await send(chat,`✅ Tipo: ${reportLabel(arg)}\n📌 ${p?.code||""} · ${p?.name||""}\n\n¿En qué formato deseas generarlo?`,formatKeyboard(id));return}
 if(action==="rv"){const {data:d}=await admin.from("assistant_drafts").select("parsed_data,project_id").eq("id",id).eq("workspace_id",link.workspace_id).maybeSingle();if(!d)return;const selection=arg==="all"?"all":String(Number(arg));await admin.from("assistant_drafts").update({parsed_data:{...(d.parsed_data||{}),report_type:"visitas",visit_selection:selection},updated_at:new Date().toISOString()}).eq("id",id);if(selection==="all")await send(chat,"✅ Seleccionaste todas las visitas. Se generará un informe profesional por cada visita en el formato que elijas.\n\n¿En qué formato deseas generarlas?",formatKeyboard(id));else{const visits=await visitsFor(d.project_id);const v=visits.find((x:any)=>String(x.visit_number)===selection);await send(chat,`✅ ${v?visitDesc(v):`Visita N.º ${selection}`}\n\n¿En qué formato deseas generarla?`,formatKeyboard(id))}return}
 if(action==="rf"){const {data:d}=await admin.from("assistant_drafts").select("*").eq("id",id).eq("workspace_id",link.workspace_id).maybeSingle();if(!d){await send(chat,"No encontré el borrador del documento.");return}await send(chat,"⏳ Preparando el informe con formato profesional, datos del expediente y evidencia disponible...");try{const r=await generateAndSend(chat,link,d,arg);const vm=r.visits.length?`\nVisitas incluidas: ${r.visits.map((v:any)=>`N.º ${v.visit_number}`).join(", ")}.`:"";const pm=r.photoCount?`\nFotografías incorporadas: ${r.photoCount}.`:"";await send(chat,`✅ Documento generado correctamente (${r.count} archivo${r.count===1?"":"s"}).${vm}${pm}\nQuedó guardado en el expediente.`)}catch(e){console.error("generate report",e);await send(chat,`No pude generar el documento: ${clean(e instanceof Error?e.message:e,700)}`)}return}
 if(action==="approve"){try{await send(chat,await approveDraft(id,link))}catch(e){await send(chat,`No pude aplicar el borrador: ${clean(e instanceof Error?e.message:e,600)}`)}return}
 if(action==="review"){await send(chat,"✏️ Envíame la corrección por texto o audio y especifica qué deseas cambiar antes de aprobar.")}}

async function engineer(text:string,workspace:string,current?:string|null){const list=await catalog(workspace);let p=resolveStrict(list,text);if(!p&&tokens(text).length===0&&current)p=list.find(x=>x.id===current);if(p){const ctx=await projectContext(p.id);const d=await gemini(`Eres el Ingeniero de Control Contractual. Proyecto: ${line(p)}. Expediente: ${ctx}. Pregunta: ${clean(text,2000)}. Responde en español claro, directo y profesional. No inventes datos.`);return{reply:clean(extractInteractionText(d),3900)||line(p),project:p}}const r=ranked(list,text,10);const d=await gemini(`Eres el Ingeniero de Control Contractual. Posibles proyectos: ${r.map(x=>line(x.p)).join("\n")}. Pregunta: ${clean(text,2000)}. No digas que no existe si hay coincidencias.`);return{reply:clean(extractInteractionText(d),3900)||"No pude identificar un único proyecto.",project:null}}

Deno.serve(async(req:Request)=>{try{if(req.method==="GET")return json({ok:true,version:"telegram-documents-v3-smart-reports",model:geminiModel});if(req.method!=="POST")return json({error:"Método no permitido"},405);const expected=await sha256(telegramToken),incoming=req.headers.get("x-telegram-bot-api-secret-token")??"";if(!incoming||incoming!==expected)return json({error:"Webhook no autorizado"},401);let u:any;try{u=await req.json()}catch{return json({error:"JSON inválido"},400)}const m=u?.message??u?.edited_message??u?.callback_query?.message,from=u?.message?.from??u?.edited_message?.from??u?.callback_query?.from,chat=m?.chat?.id,tid=from?.id;if(!chat||!tid)return json({ok:true,ignored:true});let {data:link}=await admin.from("telegram_links").select("id,workspace_id,user_id,status,current_project_id").eq("telegram_user_id",tid).eq("status","active").limit(1).maybeSingle();const text=clean(m?.text??m?.caption??"",3000),parts=text.split(/\s+/).filter(Boolean),cmd=(parts[0]||"").toLowerCase(),startCode=cmd==="/start"&&/^\d{8}$/.test(parts[1]||"")?parts[1]:null;
 if(!link&&startCode){const h=await sha256(startCode);const {data:p}=await admin.from("telegram_links").select("id,workspace_id,user_id,status").eq("link_code_hash",h).eq("status","pending").gt("link_code_expires_at",new Date().toISOString()).limit(1).maybeSingle();if(p){const {data:a}=await admin.from("telegram_links").update({telegram_user_id:tid,telegram_chat_id:chat,telegram_username:clean(from?.username,120)||null,telegram_first_name:clean(from?.first_name,120)||null,status:"active",verified_at:new Date().toISOString(),link_code_hash:null,link_code_expires_at:null,updated_at:new Date().toISOString()}).eq("id",p.id).select("id,workspace_id,user_id,status,current_project_id").single();link=a;await send(chat,"✅ Cuenta vinculada a Control Contractual.")}}
 if(!link){await send(chat,"Tu cuenta de Telegram todavía no está vinculada a Control Contractual.");return json({ok:true,linked:false})}
 if(u.callback_query){await handleCallback(u,link,chat);return json({ok:true,callback:true})}
 const type=mtype(m),f=finfo(m);const {data:inbox,error:ie}=await admin.from("assistant_inbox").upsert({workspace_id:link.workspace_id,telegram_link_id:link.id,user_id:link.user_id,telegram_update_id:u.update_id??null,telegram_message_id:m.message_id??null,telegram_chat_id:chat,message_type:type,text_content:text||null,telegram_file_id:f.id,telegram_file_unique_id:f.unique,mime_type:f.mime,payload:{media_group_id:m.media_group_id||null},status:"received"},{onConflict:"workspace_id,telegram_update_id",ignoreDuplicates:false}).select("id").single();if(ie)throw ie;
 if(cmd==="/start"){await send(chat,"✅ Telegram está vinculado. Puedes consultar proyectos, enviar fotos, audios y documentos, registrar información o pedirme cualquier informe.");return json({ok:true})}
 if(cmd==="/ayuda"){await send(chat,"/proyectos colegio — buscar\n/usar colegio — fijar proyecto activo\n/actual — ver proyecto activo\n\nPuedes pedir: ‘Genera un informe de avance y observaciones del pavimento del colegio con lo que te acabo de enviar’. Si es un informe de visita, primero te mostraré todas las visitas para que elijas cuál deseas. Después te preguntaré PDF, Word o ambos.");return json({ok:true})}
 const list=await catalog(link.workspace_id);
 if(cmd==="/proyectos"){const q=parts.slice(1).join(" "),r=q?ranked(list,q,100).map(x=>x.p):list;await sendLong(chat,`${q?`🏗️ Coincidencias para “${q}”`:`🏗️ Proyectos: ${list.length}`}\n\n${r.map((p:any,i:number)=>`${i+1}. ${line(p)}`).join("\n")||"Sin coincidencias"}`);return json({ok:true})}
 if(cmd==="/usar"){const p=resolveStrict(list,parts.slice(1).join(" "));if(!p){await send(chat,"No pude identificar un único proyecto. Escribe un nombre o código más específico.");return json({ok:true})}await admin.from("telegram_links").update({current_project_id:p.id,updated_at:new Date().toISOString()}).eq("id",link.id);await send(chat,`📌 Proyecto activo:\n${line(p)}`);return json({ok:true})}
 if(cmd==="/actual"){const p=list.find(x=>x.id===link.current_project_id);await send(chat,p?`📌 ${line(p)}`:"No hay proyecto activo.");return json({ok:true})}
 if(isReportRequest(text)){let p=resolveStrict(list,text);if(!p&&tokens(text).length===0&&link.current_project_id)p=list.find(x=>x.id===link.current_project_id);if(!p&&link.current_project_id&&/\b(este|ese|actual|proyecto)\b/i.test(text))p=list.find(x=>x.id===link.current_project_id);if(!p){const opts=ranked(list,text,5).map(x=>line(x.p)).join("\n");await send(chat,`No pude identificar el proyecto con suficiente seguridad.${opts?`\n\nPosibles coincidencias:\n${opts}`:""}\n\nUsa /usar <nombre o código> o escribe el nombre más completo.`);return json({ok:true})}const rt=reportType(text),r=await createReportDraft(link,p,text,rt,list);const counts={photo:r.evidence.filter((x:any)=>x.evidence_type==="photo").length,audio:r.evidence.filter((x:any)=>/voice|audio/.test(x.evidence_type)).length,document:r.evidence.filter((x:any)=>x.evidence_type==="document").length};const evMsg=r.evidence.length?`\nMaterial reciente incorporado: ${counts.photo} foto(s), ${counts.audio} audio(s), ${counts.document} documento(s).`:"\nNo detecté archivos recientes; usaré la información registrada en el expediente y tu solicitud.";if(r.contextText)await send(chat,`🧠 Tomaré también en cuenta las indicaciones recientes que me has enviado para este proyecto.${evMsg}`);if(rt==="visitas")await askVisit(chat,r.draftId,p);else await send(chat,`📄 Prepararé un informe profesional sobre lo que solicitaste.\n\n📌 ${line(p)}${evMsg}\n\n¿En qué formato deseas generarlo?`,formatKeyboard(r.draftId));await admin.from("assistant_inbox").update({project_id:p.id,status:"processed",processed_at:new Date().toISOString()}).eq("id",inbox.id);return json({ok:true,draft:r.draftId})}
 if(type==="location"){await admin.from("assistant_inbox").update({project_id:link.current_project_id||null,status:"processed",processed_at:new Date().toISOString()}).eq("id",inbox.id);await send(chat,"📍 Ubicación guardada como evidencia.");return json({ok:true})}
 if(["photo","voice","audio","document"].includes(type)){try{if(!f.id)throw new Error("Archivo no disponible");let p=resolveStrict(list,text)||list.find(x=>x.id===link.current_project_id)||null;const dl=await downloadTG(f.id);const path=`${link.workspace_id}/${p?.id||"unassigned"}/${todayHN()}/${Date.now()}_${safe(f.name||"archivo")}`;const up=await admin.storage.from("telegram-evidence").upload(path,dl.bytes,{contentType:f.mime||"application/octet-stream",upsert:false});if(up.error)throw up.error;const a=await analyzeMedia(dl.bytes,f.mime||"application/octet-stream",type,text,p,list);if(!p&&a.project_query)p=resolveStrict(list,String(a.project_query));if(p){await admin.from("telegram_links").update({current_project_id:p.id,updated_at:new Date().toISOString()}).eq("id",link.id);link.current_project_id=p.id}const {data:e,error:ee}=await admin.from("project_evidence").insert({workspace_id:link.workspace_id,project_id:p?.id||null,inbox_id:inbox.id,evidence_type:type,storage_path:path,mime_type:f.mime,file_name:f.name,size_bytes:dl.size,telegram_file_unique_id:f.unique,extracted_text:a.transcript||a.summary||null,analysis:a,created_by:link.user_id}).select("id").single();if(ee)throw ee;await admin.from("assistant_inbox").update({project_id:p?.id||null,status:"processed",processed_at:new Date().toISOString(),payload:{evidence_id:e?.id,path,analysis:a}}).eq("id",inbox.id);const need=["register_visit","add_report","add_evidence"].includes(a.intent);if(need&&p){const dtype=a.intent==="register_visit"?"visit":"report_input";const {data:d,error:de}=await admin.from("assistant_drafts").insert({workspace_id:link.workspace_id,inbox_id:inbox.id,project_id:p.id,draft_type:dtype,title:a.summary||"Borrador desde Telegram",source_text:a.transcript||null,summary:a.summary||null,parsed_data:a,status:"draft",created_by:link.user_id}).select("id").single();if(de)throw de;await send(chat,`🧠 Análisis completado\n\n📌 ${line(p)}\n\n${clean(a.summary,1500)}\n\n¿Deseas aplicar esta información al expediente?`,{inline_keyboard:[[{text:"✅ Aprobar",callback_data:`approve:${d.id}`},{text:"✏️ Revisar",callback_data:`review:${d.id}`}],[{text:"❌ Cancelar",callback_data:`cancel:${d.id}`}]]})}else await send(chat,`🧠 Análisis completado\n\n📌 ${p?line(p):"Proyecto no identificado"}\n\n${clean(a.summary,1800)}${a.transcript?`\n\nTranscripción:\n${clean(a.transcript,1000)}`:""}`);return json({ok:true})}catch(e){await admin.from("assistant_inbox").update({status:"error",error_message:clean(e instanceof Error?e.message:e,700),processed_at:new Date().toISOString()}).eq("id",inbox.id);await send(chat,`No pude procesar completamente el archivo: ${clean(e instanceof Error?e.message:e,700)}`);return json({ok:false})}}
 if(!text)return json({ok:true});try{const r=await engineer(text,link.workspace_id,link.current_project_id);if(r.project){await admin.from("telegram_links").update({current_project_id:r.project.id,updated_at:new Date().toISOString()}).eq("id",link.id);await admin.from("assistant_inbox").update({project_id:r.project.id,status:"processed",processed_at:new Date().toISOString()}).eq("id",inbox.id)}else await admin.from("assistant_inbox").update({status:"processed",processed_at:new Date().toISOString()}).eq("id",inbox.id);await send(chat,r.reply);return json({ok:true})}catch(e){await admin.from("assistant_inbox").update({status:"error",error_message:clean(e instanceof Error?e.message:e,700),processed_at:new Date().toISOString()}).eq("id",inbox.id);await send(chat,`No pude completar la consulta: ${clean(e instanceof Error?e.message:e,700)}`);return json({ok:false})}}
 catch(e){console.error("webhook fatal",e);return json({ok:false,error:clean(e instanceof Error?e.message:e,700)},500)}});