import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.57.0";
import jpeg from "npm:jpeg-js@0.4.4";

const U=Deno.env.get("SUPABASE_URL")??"";
const K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??"";
const T=Deno.env.get("TELEGRAM_BOT_TOKEN")??"";
const db=createClient(U,K,{auth:{persistSession:false,autoRefreshToken:false}});
const clean=(v:any,n=500)=>String(v??"").replace(/[\u0000-\u001f\u007f]/g," ").trim().slice(0,n);
const json=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{"content-type":"application/json","cache-control":"no-store"}});
async function sha(v:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return[...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function tg(method:string,body:any){const r=await fetch(`https://api.telegram.org/bot${T}/${method}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),d=await r.json().catch(()=>({}));if(!r.ok||d?.ok===false)throw new Error(d?.description||`Telegram ${r.status}`);return d}
function choosePhoto(arr:any[]){if(!Array.isArray(arr)||!arr.length)return null;return [...arr].sort((a,b)=>(Number(a.width||0)*Number(a.height||0))-(Number(b.width||0)*Number(b.height||0))).pop()||null}
async function downloadTG(fileId:string){const meta=await tg("getFile",{file_id:fileId}),path=meta?.result?.file_path;if(!path)throw new Error("Telegram no devolvió file_path");const r=await fetch(`https://api.telegram.org/file/bot${T}/${path}`);if(!r.ok)throw new Error(`No se pudo descargar la fotografía (${r.status})`);const b=new Uint8Array(await r.arrayBuffer());if(b.byteLength>15*1024*1024)throw new Error("La fotografía supera 15 MB");return b}
function completeJpeg(b:Uint8Array){return b.length>1200&&b[0]===0xff&&b[1]===0xd8&&b[b.length-2]===0xff&&b[b.length-1]===0xd9}
function suspiciousGray(decoded:any){const w=Number(decoded?.width||0),h=Number(decoded?.height||0),d=decoded?.data;if(!w||!h||!d)return true;const xs=Math.max(1,Math.floor(w/160)),ys=Math.max(1,Math.floor(h/120));let total=0,neutral=0,run=0,maxRun=0;for(let y=Math.floor(h*.10);y<h;y+=ys){let row=0,rowNeutral=0;for(let x=0;x<w;x+=xs){const i=(y*w+x)*4,r=d[i],g=d[i+1],b=d[i+2];row++;total++;const n=Math.abs(r-g)<=3&&Math.abs(g-b)<=3&&r>=116&&r<=142;if(n){rowNeutral++;neutral++}}const ratio=row?rowNeutral/row:0;if(ratio>=.82){run++;maxRun=Math.max(maxRun,run)}else run=0}return(total?neutral/total:1)>.28||maxRun*ys>=Math.max(10,Math.floor(h*.08))}
function validate(bytes:Uint8Array){if(!completeJpeg(bytes))return{valid:false,reason:"archivo JPEG incompleto o truncado"};try{const dec=jpeg.decode(bytes,{useTArray:true,formatAsRGBA:true,tolerantDecoding:false,maxResolutionInMP:35,maxMemoryUsageInMB:512} as any);const w=Number(dec?.width||0),h=Number(dec?.height||0);if(!w||!h)return{valid:false,reason:"no se pudo decodificar la imagen"};if(w<320||h<240)return{valid:false,reason:`resolución demasiado baja (${w}×${h})`,width:w,height:h};if(suspiciousGray(dec))return{valid:false,reason:"se detectaron bloques grises o datos dañados",width:w,height:h};return{valid:true,width:w,height:h,size:bytes.byteLength}}catch(e){return{valid:false,reason:clean(e instanceof Error?e.message:e,220)||"error de decodificación"}}}
Deno.serve(async req=>{try{if(req.method==="GET")return json({ok:true,service:"incoming-visit-photo-validator",version:"1.0-realtime-integrity"});if(req.method!=="POST")return json({error:"method"},405);if((req.headers.get("x-internal-image-secret")??"")!==await sha(T))return json({error:"unauthorized"},401);const b=await req.json().catch(()=>({})),linkId=clean(b.link_id,100),u=b.update||{},m=u?.message??u?.edited_message;if(!linkId||!m?.photo?.length)return json({ok:false,error:"invalid request"},400);const {data:l}=await db.from("telegram_links").select("id,workspace_id,status").eq("id",linkId).eq("status","active").maybeSingle();if(!l)return json({ok:false,error:"link not found"},404);const {data:s}=await db.from("assistant_visit_sessions").select("id,project_id,status").eq("telegram_link_id",linkId).eq("status","active").order("created_at",{ascending:false}).limit(1).maybeSingle();if(!s)return json({ok:true,active_visit:false,valid:true,skipped:true});const p=choosePhoto(m.photo);if(!p?.file_id)return json({ok:false,error:"photo file not found"},400);const bytes=await downloadTG(p.file_id),v=validate(bytes);return json({ok:true,active_visit:true,...v,visit_session_id:s.id,project_id:s.project_id,file_unique_id:p.file_unique_id||null})}catch(e){console.error("incoming-visit-photo-validator",e);return json({ok:false,error:clean(e instanceof Error?e.message:e,600)},500)}});